---
- name: Ensure replication VIP pools
  vastdata.vms.vippools:
    vms: "{{ protectedpath_vms[item.cluster] }}"
    id: "{{ item.id | default(omit) }}"
    bgp_config_id: "{{ item.bgp_config_id | default(omit) }}"
    client_monitoring_ips: "{{ item.client_monitoring_ips | default(omit) }}"
    cluster_id: "{{ item.cluster_id | default(omit) }}"
    cnode_ids: "{{ item.cnode_ids | default(omit) }}"
    cnode_names: "{{ item.cnode_names | default(omit) }}"
    domain_name: "{{ item.domain_name | default(omit) }}"
    enable_l3: "{{ item.enable_l3 | default(omit) }}"
    enable_weighted_balancing: "{{ item.enable_weighted_balancing | default(omit) }}"
    enabled: "{{ item.enabled | default(omit) }}"
    end_ip: "{{ item.end_ip | default(omit) }}"
    gw_ip: "{{ item.gw_ip | default(omit) }}"
    gw_ipv6: "{{ item.gw_ipv6 | default(omit) }}"
    ip_ranges: "{{ item.ip_ranges | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    peer_asn: "{{ item.peer_asn | default(omit) }}"
    port_membership: "{{ item.port_membership | default(omit) }}"
    role: "{{ item.role | default(omit) }}"
    start_ip: "{{ item.start_ip | default(omit) }}"
    subnet_cidr: "{{ item.subnet_cidr | default(omit) }}"
    subnet_cidr_ipv6: "{{ item.subnet_cidr_ipv6 | default(omit) }}"
    tenant_id: "{{ item.tenant_id | default(omit) }}"
    vast_asn: "{{ item.vast_asn | default(omit) }}"
    vlan: "{{ item.vlan | default(omit) }}"
    vms_preferred: "{{ item.vms_preferred | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    wait: "{{ item.wait | default(omit) }}"
    wait_timeout: "{{ item.wait_timeout | default(omit) }}"
  loop: "{{ vippools }}"
  loop_control:
    label: "{{ item.cluster }}:{{ item.name | default('?') }}"
