"""Manager class for activedirectory resources.

This module contains the ActivedirectoryManager class which encapsulates
business logic for activedirectory operations.

Generated by VAST Ansible Generator.
"""

from typing import Any, Dict

from ..managers.base import ResourceManager


class ActivedirectoryManager(ResourceManager):
    """Activedirectory resource manager.

    Provides CRUD operations and business logic for activedirectory resources.
    """

    resource_name = "activedirectory"
    lookup_field = "machine_account_name"

    # Async operation flags
    async_create = False
    async_update = True
    async_delete = False

    def is_operation_healthy(self, resource_id: int) -> Dict[str, Any]:
        """Perform is_operation_healthy operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].is_operation_healthy.post()
            return {"changed": True, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to is_operation_healthy: {str(e)}") from e

    def refresh(self, resource_id: int) -> Dict[str, Any]:
        """Perform refresh operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].refresh.patch()
            return {"changed": True, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to refresh: {str(e)}") from e

    def domains(self, resource_id: int) -> Dict[str, Any]:
        """Perform domains operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].domains.get()
            return {"changed": False, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to domains: {str(e)}") from e

    def dcs(self, resource_id: int) -> Dict[str, Any]:
        """Perform dcs operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].dcs.get()
            return {"changed": False, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to dcs: {str(e)}") from e

    def gcs(self, resource_id: int) -> Dict[str, Any]:
        """Perform gcs operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].gcs.get()
            return {"changed": False, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to gcs: {str(e)}") from e

    def current_gc(self, resource_id: int) -> Dict[str, Any]:
        """Perform current_gc operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].current_gc.get()
            return {"changed": False, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to current_gc: {str(e)}") from e

    def change_machine_account_password(self, resource_id: int) -> Dict[str, Any]:
        """Perform change_machine_account_password operation.

        Args:
            resource_id: Resource ID

        Returns:
            Operation result

        Raises:
            VastAPIError: On API errors
        """
        from ..errors import VastAPIError

        try:
            result = self.client.api.activedirectory[resource_id].change_machine_account_password.post()
            return {"changed": True, "result": result}
        except Exception as e:
            raise VastAPIError(f"Failed to change_machine_account_password: {str(e)}") from e
