#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for iamrole_revoke_access_keys module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import iamrole_revoke_access_keys


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert iamrole_revoke_access_keys is not None
        assert hasattr(iamrole_revoke_access_keys, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(iamrole_revoke_access_keys, "DOCUMENTATION")
        assert len(iamrole_revoke_access_keys.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(iamrole_revoke_access_keys, "EXAMPLES")
        assert len(iamrole_revoke_access_keys.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(iamrole_revoke_access_keys, "RETURN")
        assert len(iamrole_revoke_access_keys.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(iamrole_revoke_access_keys, "ARGUMENT_SPEC")
        assert isinstance(iamrole_revoke_access_keys.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = iamrole_revoke_access_keys.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = iamrole_revoke_access_keys.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = iamrole_revoke_access_keys.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestSubEndpointSpec:
    """Test sub-endpoint ARGUMENT_SPEC entries."""

    def test_has_parent_id_param(self):
        """Test parent ID parameter is present and required."""
        spec = iamrole_revoke_access_keys.ARGUMENT_SPEC
        assert "iamrole_id" in spec
        assert spec["iamrole_id"]["required"] is True
        assert spec["iamrole_id"]["type"] == "int"

    def test_no_state_param(self):
        """Test no state parameter."""
        spec = iamrole_revoke_access_keys.ARGUMENT_SPEC
        assert "state" not in spec


# END AUTOGENERATED TESTS
