#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for kerberos_keytab module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import kerberos_keytab


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert kerberos_keytab is not None
        assert hasattr(kerberos_keytab, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(kerberos_keytab, "DOCUMENTATION")
        assert len(kerberos_keytab.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(kerberos_keytab, "EXAMPLES")
        assert len(kerberos_keytab.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(kerberos_keytab, "RETURN")
        assert len(kerberos_keytab.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(kerberos_keytab, "ARGUMENT_SPEC")
        assert isinstance(kerberos_keytab.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestSubEndpointSpec:
    """Test sub-endpoint ARGUMENT_SPEC entries."""

    def test_has_parent_id_param(self):
        """Test parent ID parameter is present and required."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        assert "kerberos_id" in spec
        assert spec["kerberos_id"]["required"] is True
        assert spec["kerberos_id"]["type"] == "int"

    def test_no_state_param(self):
        """Test no state parameter."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        assert "state" not in spec

    def test_has_body_params(self):
        """Test body parameters are present."""
        spec = kerberos_keytab.ARGUMENT_SPEC
        expected = ["admin_password", "admin_username", "keytab_file"]
        for param in expected:
            assert param in spec, f"Missing param: {param}"


# END AUTOGENERATED TESTS
