#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for user_key module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import user_key


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert user_key is not None
        assert hasattr(user_key, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(user_key, "DOCUMENTATION")
        assert len(user_key.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(user_key, "EXAMPLES")
        assert len(user_key.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(user_key, "RETURN")
        assert len(user_key.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(user_key, "ARGUMENT_SPEC")
        assert isinstance(user_key.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = user_key.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = user_key.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = user_key.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestSubEndpointSpec:
    """Test sub-endpoint ARGUMENT_SPEC entries."""

    def test_has_parent_id_param(self):
        """Test parent ID parameter is present and required."""
        spec = user_key.ARGUMENT_SPEC
        assert "user_id" in spec
        assert spec["user_id"]["required"] is True
        assert spec["user_id"]["type"] == "int"

    def test_has_state_param(self):
        """Test state parameter with present/absent choices."""
        spec = user_key.ARGUMENT_SPEC
        assert "state" in spec
        assert spec["state"]["choices"] == ["present", "absent"]
        assert spec["state"]["default"] == "present"

    def test_has_body_params(self):
        """Test body parameters are present."""
        spec = user_key.ARGUMENT_SPEC
        expected = ["access_key", "enabled", "tenant_id"]
        for param in expected:
            assert param in spec, f"Missing param: {param}"


# END AUTOGENERATED TESTS
