#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for ldaps_info module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import ldaps_info


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert ldaps_info is not None
        assert hasattr(ldaps_info, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(ldaps_info, "DOCUMENTATION")
        assert len(ldaps_info.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(ldaps_info, "EXAMPLES")
        assert len(ldaps_info.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(ldaps_info, "RETURN")
        assert len(ldaps_info.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(ldaps_info, "ARGUMENT_SPEC")
        assert isinstance(ldaps_info.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = ldaps_info.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = ldaps_info.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = ldaps_info.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestInfoModule:
    """Test read-only info-module contract."""

    def test_supports_check_mode(self):
        """Info modules declare no state-changing CRUD params."""
        spec = ldaps_info.ARGUMENT_SPEC
        assert "wait" not in spec
        assert "wait_timeout" not in spec


# END AUTOGENERATED TESTS
