#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for vms_network_settings module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import vms_network_settings


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert vms_network_settings is not None
        assert hasattr(vms_network_settings, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(vms_network_settings, "DOCUMENTATION")
        assert len(vms_network_settings.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(vms_network_settings, "EXAMPLES")
        assert len(vms_network_settings.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(vms_network_settings, "RETURN")
        assert len(vms_network_settings.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(vms_network_settings, "ARGUMENT_SPEC")
        assert isinstance(vms_network_settings.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestSubEndpointSpec:
    """Test sub-endpoint ARGUMENT_SPEC entries."""

    def test_has_parent_id_param(self):
        """Test parent ID parameter is present and required."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "vms_id" in spec
        assert spec["vms_id"]["required"] is True
        assert spec["vms_id"]["type"] == "int"

    def test_has_state_param(self):
        """Test state parameter with present/absent choices."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "state" in spec
        assert spec["state"]["choices"] == ["present", "absent"]
        assert spec["state"]["default"] == "present"

    def test_has_async_params(self):
        """Test async wait parameters are present."""
        spec = vms_network_settings.ARGUMENT_SPEC
        assert "wait" in spec
        assert spec["wait"]["type"] == "bool"
        assert "wait_timeout" in spec
        assert spec["wait_timeout"]["type"] == "int"

    def test_has_body_params(self):
        """Test body parameters are present."""
        spec = vms_network_settings.ARGUMENT_SPEC
        expected = [
            "auto_ports_ext_iface",
            "b2b_ipmi",
            "dns",
            "eth_mtu",
            "ext_netmask",
            "external_gateways",
            "hosts",
            "ib_mtu",
            "ipmi_gateway",
            "ipmi_netmask",
            "management_vips",
            "ntp",
        ]
        for param in expected:
            assert param in spec, f"Missing param: {param}"


# END AUTOGENERATED TESTS
