#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for nonlocal_user module."""

# BEGIN AUTOGENERATED TESTS
from ansible_collections.vastdata.vms.plugins.modules import nonlocal_user


class TestModuleStructure:
    """Test module structure and documentation."""

    def test_module_imports(self):
        """Test that the module can be imported."""
        assert nonlocal_user is not None
        assert hasattr(nonlocal_user, "main")

    def test_has_documentation(self):
        """Test that the module has DOCUMENTATION."""
        assert hasattr(nonlocal_user, "DOCUMENTATION")
        assert len(nonlocal_user.DOCUMENTATION) > 0

    def test_has_examples(self):
        """Test that the module has EXAMPLES."""
        assert hasattr(nonlocal_user, "EXAMPLES")
        assert len(nonlocal_user.EXAMPLES) > 0

    def test_has_return(self):
        """Test that the module has RETURN documentation."""
        assert hasattr(nonlocal_user, "RETURN")
        assert len(nonlocal_user.RETURN) > 0

    def test_has_argument_spec(self):
        """Test that the module has ARGUMENT_SPEC."""
        assert hasattr(nonlocal_user, "ARGUMENT_SPEC")
        assert isinstance(nonlocal_user.ARGUMENT_SPEC, dict)


class TestConnectionParams:
    """Test connection parameters in ARGUMENT_SPEC."""

    def test_has_vms_dict(self):
        """Test vms parameter dict is present and required."""
        spec = nonlocal_user.ARGUMENT_SPEC
        assert "vms" in spec
        assert spec["vms"]["required"] is True
        assert spec["vms"]["type"] == "dict"

    def test_has_host(self):
        """Test host parameter is required within vms."""
        spec = nonlocal_user.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "host" in vms_options
        assert vms_options["host"]["required"] is True

    def test_has_auth_params(self):
        """Test authentication parameters exist within vms."""
        spec = nonlocal_user.ARGUMENT_SPEC
        assert "vms" in spec
        vms_options = spec["vms"]["options"]
        assert "token" in vms_options
        assert "username" in vms_options
        assert "password" in vms_options


class TestSubEndpointSpec:
    """Test sub-endpoint ARGUMENT_SPEC entries."""

    def test_has_state_param(self):
        """Test state parameter with present/absent choices."""
        spec = nonlocal_user.ARGUMENT_SPEC
        assert "state" in spec
        assert spec["state"]["choices"] == ["present", "absent"]
        assert spec["state"]["default"] == "present"

    def test_has_body_params(self):
        """Test body parameters are present."""
        spec = nonlocal_user.ARGUMENT_SPEC
        expected = [
            "allow_create_bucket",
            "allow_delete_bucket",
            "login_name",
            "s3_policies_ids",
            "s3_superuser",
            "sid",
            "tenant_id",
            "uid",
            "username",
        ]
        for param in expected:
            assert param in spec, f"Missing param: {param}"


# END AUTOGENERATED TESTS
