#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for protectionpolicies module."""

# BEGIN AUTOGENERATED TESTS
import sys
from pathlib import Path

# Add collection root to path for importing module_utils
collection_root = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(collection_root))

from plugins.module_utils.vast.diff import (
    compute_patch,
    normalize_resource,
)
from plugins.module_utils.vast.schema_overrides import (
    get_overrides,
)


class TestNormalize:
    """Test normalize_resource function."""

    def test_normalize_removes_read_only_fields(self):
        """Verify read-only fields are removed."""
        resource = {"id": 1, "name": "test"}
        overrides = get_overrides("protectionpolicies")
        result = normalize_resource(resource, overrides)
        assert "id" not in result

    def test_normalize_preserves_writable_fields(self):
        """Verify writable fields are preserved."""
        resource = {"name": "test-value"}
        overrides = get_overrides("protectionpolicies")
        result = normalize_resource(resource, overrides)
        assert "name" in result


class TestComputePatch:
    """Test compute_patch function."""

    def test_no_changes(self):
        """Verify no patch when values match."""
        current = {"name": "test"}
        desired = {"name": "test"}
        overrides = get_overrides("protectionpolicies")
        patch = compute_patch(current, desired, overrides)
        assert patch == {}

    def test_detects_change(self):
        """Verify patch detects changes."""
        current = {"name": "old"}
        desired = {"name": "new"}
        overrides = get_overrides("protectionpolicies")
        patch = compute_patch(current, desired, overrides)
        assert patch == {"name": "new"}


# END AUTOGENERATED TESTS


class TestFramesIdempotency:
    """Verify frames field comparison is unit- and default-aware."""

    overrides = get_overrides("protectionpolicies")

    def _patch_for(self, current_frames, desired_frames):
        current = {"frames": current_frames, "name": "p"}
        desired = {"frames": desired_frames, "name": "p"}
        current_n = normalize_resource(current, self.overrides, exclude_immutable=True, user_resource=desired)
        desired_n = normalize_resource(desired, self.overrides, exclude_immutable=True)
        return compute_patch(current_n, desired_n, self.overrides)

    def test_unit_normalization_7D_equals_1W(self):
        """Bug reproducer: server returns '1W' when user wrote '7D'."""
        current = [
            {"every": "1W", "start-at": "2025-08-01 09:00:00", "keep-local": "2W", "keep-remote": "0s"},
            {"every": "1W", "start-at": "2025-08-01 09:00:00", "keep-local": "8D", "keep-remote": "0s"},
        ]
        desired = [
            {"every": "7D", "keep-local": "14D", "keep-remote": "0s", "start-at": "2025-08-01 09:00:00"},
            {"every": "7D", "keep-local": "8D", "keep-remote": "0s", "start-at": "2025-08-01 09:00:00"},
        ]
        assert self._patch_for(current, desired) == {}

    def test_unit_normalization_24H_equals_1D(self):
        """Server normalizes 24H -> 1D."""
        current = [{"every": "1D", "keep-local": "1W", "keep-remote": "0s"}]
        desired = [{"every": "24H", "keep-local": "7D", "keep-remote": "0s"}]
        assert self._patch_for(current, desired) == {}

    def test_default_keep_remote_dropped(self):
        """User omits keep-remote; server adds 'keep-remote: 0s'. No diff."""
        current = [{"every": "7D", "keep-local": "14D", "keep-remote": "0s", "start-at": "2025-08-01 09:00:00"}]
        desired = [{"every": "7D", "keep-local": "14D", "start-at": "2025-08-01 09:00:00"}]
        assert self._patch_for(current, desired) == {}

    def test_real_change_is_detected(self):
        """Genuine differences must still produce a patch."""
        current = [{"every": "7D", "keep-local": "14D", "keep-remote": "0s"}]
        desired = [{"every": "7D", "keep-local": "30D", "keep-remote": "0s"}]
        patch = self._patch_for(current, desired)
        assert "frames" in patch
        assert patch["frames"][0]["keep-local"] == "30D"

    def test_different_frame_count_produces_patch(self):
        """Adding/removing a frame must trigger a change."""
        current = [{"every": "7D", "keep-local": "14D", "keep-remote": "0s"}]
        desired = [
            {"every": "7D", "keep-local": "14D", "keep-remote": "0s"},
            {"every": "7D", "keep-local": "8D", "keep-remote": "0s"},
        ]
        assert "frames" in self._patch_for(current, desired)
