#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Unit tests for ldaps module."""

# BEGIN AUTOGENERATED TESTS
import sys
from pathlib import Path

# Add collection root to path for importing module_utils
collection_root = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(collection_root))

from plugins.module_utils.vast.diff import (
    compute_patch,
    normalize_resource,
)
from plugins.module_utils.vast.schema_overrides import (
    get_overrides,
)


class TestNormalize:
    """Test normalize_resource function."""

    def test_normalize_removes_read_only_fields(self):
        """Verify read-only fields are removed."""
        resource = {"id": 1, "domain_name": "test", "name": "test"}
        overrides = get_overrides("ldaps")
        result = normalize_resource(resource, overrides)
        assert "id" not in result

    def test_normalize_preserves_writable_fields(self):
        """Verify writable fields are preserved."""
        resource = {"domain_name": "test-value"}
        overrides = get_overrides("ldaps")
        result = normalize_resource(resource, overrides)
        assert "domain_name" in result


class TestComputePatch:
    """Test compute_patch function."""

    def test_no_changes(self):
        """Verify no patch when values match."""
        current = {"domain_name": "test"}
        desired = {"domain_name": "test"}
        overrides = get_overrides("ldaps")
        patch = compute_patch(current, desired, overrides)
        assert patch == {}

    def test_detects_change(self):
        """Verify patch detects changes."""
        current = {"domain_name": "old"}
        desired = {"domain_name": "new"}
        overrides = get_overrides("ldaps")
        patch = compute_patch(current, desired, overrides)
        assert patch == {"domain_name": "new"}


# END AUTOGENERATED TESTS
