"""Registry of modules with manual customizations outside AUTOGENERATED blocks.

When a module needs code that the generator cannot produce (e.g. a custom
``validate_run_params`` override), the custom code is placed *between*
AUTOGENERATED marker pairs -- the generator only replaces content *inside*
the markers, so the custom code survives regeneration.

This registry declares which modules carry such customizations and what
string markers to look for.  The code generator checks this after writing
a module file; if expected markers are missing it fails loudly instead of
silently losing the custom code.
"""

CUSTOMIZED_MODULES = {
    "cnodes": {
        "description": (
            "CNode-specific validate_run_params override: allows creation "
            "by ip (instead of name/id) and loopback auto-discovery, "
            "plus CNODE_STATE_CHANGE_TIMEOUT for wait_timeout default."
        ),
        "markers": [
            "_apply_cnode_customizations()",
            "CnodeResource.validate_run_params = _cnode_validate_run_params",
        ],
    },
}
