"""Base Resource class for Ansible modules.

Provides common CRUD functionality for all resource modules,
eliminating code duplication across 100+ generated modules.
"""

import re
from typing import Any, Dict, Optional, Set

from ansible.module_utils.basic import AnsibleModule

from .auth import build_connection, validate_auth
from .client import VastClient
from .diff import compute_patch, normalize_resource
from .errors import VastAPIError
from .schema_overrides import get_overrides
from .timeouts import DEFAULT_TASK_TIMEOUT
from .version import ensure_supported_version


class BaseResource:
    """Base class for all Ansible module resources.

    Provides common CRUD operations and idempotent lifecycle management.

    Subclasses must define:
    - resource_name: str  # e.g., "alarms", "views"
    - singular: str       # e.g., "alarm", "view"
    - lookup_field: str   # e.g., "name", "path"

    Subclasses may override:
    - async_create: bool = False
    - async_update: bool = False
    - async_delete: bool = False
    - include_ephemeral_in_updates: bool = False  # Set True to allow password updates (breaks idempotency)
    - get(), create(), update(), delete() methods for custom behavior
    """

    resource_name: str = NotImplemented
    singular: str = NotImplemented
    lookup_field: str = "name"

    # Override these for async resources
    async_create: bool = False
    async_update: bool = False
    async_delete: bool = False

    # Override this to include ephemeral fields (passwords/secrets) in update patches
    # This breaks idempotency but allows password updates. Default False for idempotency.
    include_ephemeral_in_updates: bool = False

    # Swagger-derived field restrictions (auto-generated by code generator)
    create_only_fields: Set[str] = set()  # Fields only valid during creation (excluded from updates)
    update_only_fields: Set[str] = set()  # Fields only valid during updates (excluded from creates)

    def __init__(self, module: AnsibleModule):
        """Initialize the resource manager.

        Args:
            module: AnsibleModule instance
        """
        self.module = module
        self.params = module.params
        self.check_mode = module.check_mode

        # Validate authentication
        try:
            validate_auth(self.params)
        except Exception as e:
            module.fail_json(msg=str(e))

        # Build connection and client
        conn = build_connection(self.params)
        try:
            self.client = VastClient(conn)
        except RuntimeError as e:
            module.fail_json(msg=str(e))

        self.client.debug = conn.debug

        # Validate product version
        ensure_supported_version(module, self.client, min_version=(5, 4, 0), max_version=(5, 5, 0))

        # Get schema overrides for this resource
        self.overrides = get_overrides(self.resource_name)

    # -- debug trace helpers -------------------------------------------------

    _MAX_DEBUG_TRACES = 20

    _AUTH_HEADER_RE = re.compile(
        r"(Authorization:\s*(?:Bearer|Basic|Api-Token)\s+)\S+",
        re.IGNORECASE,
    )
    _TOKEN_QUERY_RE = re.compile(
        r"([\?&](?:token|api_key|access_token)=)[^&\s]+",
        re.IGNORECASE,
    )

    def _emit_debug_traces(self) -> None:
        """Emit collected HTTP debug traces as Ansible warnings.

        Uses ``pop_debug_traces()`` so the buffer is cleared after retrieval.
        Only the last ``_MAX_DEBUG_TRACES`` entries are shown; earlier ones are
        noted with a count.
        """
        if not self.client.debug:
            return
        traces = self.client.pop_debug_traces()
        if not traces:
            return
        if len(traces) > self._MAX_DEBUG_TRACES:
            self.module.warn(f"[VAST HTTP] ({len(traces) - self._MAX_DEBUG_TRACES} earlier traces omitted)")
        for trace in traces[-self._MAX_DEBUG_TRACES :]:
            self.module.warn(f"[VAST HTTP] {self._sanitize_trace(trace)}")

    def _sanitize_trace(self, trace: str) -> str:
        """Scrub secrets from a debug trace string."""
        conn = self.client._connection
        for secret in (conn.password, conn.token):
            if secret:
                trace = trace.replace(secret, "***")
        trace = self._AUTH_HEADER_RE.sub(r"\1***", trace)
        trace = self._TOKEN_QUERY_RE.sub(r"\1***", trace)
        return trace

    # -- field helpers -------------------------------------------------------

    def _get_field_value(self, resource: Dict[str, Any], field_name: str) -> Any:
        """Get field value from resource, handling nested objects.

        The API often returns nested objects (e.g., local_provider: {id: 1, name: "default"}),
        but module parameters use flat IDs (e.g., local_provider_id: 1).
        This function handles both cases.
        """
        # Try direct access first
        value = resource.get(field_name)
        if value is not None:
            return value

        # If field ends with _id, try nested object access
        # e.g., local_provider_id -> local_provider.id
        if field_name.endswith("_id"):
            nested_field = field_name[:-3]  # Remove "_id" suffix
            nested_obj = resource.get(nested_field)
            if isinstance(nested_obj, dict):
                return nested_obj.get("id")
            # Handle case where nested object is already an int
            if isinstance(nested_obj, int):
                return nested_obj

        return None

    def _is_not_found_error(self, exception: Exception) -> bool:
        """Check if exception looks like a 404 Not Found error.

        Args:
            exception: Exception from API call

        Returns:
            True if this looks like a not-found error, False otherwise
        """
        # Check common patterns in exception messages
        err_str = str(exception).lower()
        return any(
            pattern in err_str
            for pattern in [
                "404",
                "not found",
                "does not exist",
                "no such",
                "resource not found",
            ]
        )

    def _needs_detail_fetch(self, list_result: Dict[str, Any]) -> bool:
        """Check if user wants fields that are missing from list result.

        Compares user's desired state with list endpoint result to determine
        if a detail endpoint fetch is needed to get complete data.

        Args:
            list_result: Resource dict from list endpoint

        Returns:
            True if detail fetch needed, False if list result is sufficient

        Example:
            User wants: {path: "/foo", bucket_logging: {...}}
            List has:   {path: "/foo"}
            Missing:    bucket_logging
            → Returns True (refetch needed)
        """
        if "id" not in list_result:
            return False  # Can't fetch detail without ID

        # Get user's desired state
        desired = self.build_desired_state()
        if not desired:
            return False  # No desired state, list result is fine

        # Check if user wants any fields that list doesn't have
        list_keys = set(list_result.keys())
        desired_keys = set(desired.keys())

        missing_fields = desired_keys - list_keys

        # If user wants fields not in list result, we need detail fetch
        return len(missing_fields) > 0

    def get(
        self,
        lookup_value: Optional[str] = None,
        resource_id: Optional[int] = None,
        unique_constraints: Optional[Dict[str, Any]] = None,
    ) -> Optional[Dict[str, Any]]:
        """Get resource by lookup field or ID, with optional composite key filtering.

        Args:
            lookup_value: Value of the lookup field (e.g., name="foo")
            resource_id: Optional ID for direct lookup (bypasses lookup field search)
            unique_constraints: Optional dict of fields that together uniquely identify the resource

        Returns:
            Resource dict if found, None otherwise

        Raises:
            VastAPIError: On API errors (except 404/not-found)

        Note: If unique_constraints is provided, multiple matches are filtered to find the exact resource.
        """
        try:
            api = self.client.api[self.resource_name]

            # If ID provided, use direct ID lookup (most reliable)
            if resource_id is not None:
                try:
                    return api[resource_id].first()
                except Exception as e:
                    # Only treat genuine not-found as None; re-raise auth/connection errors
                    if self._is_not_found_error(e):
                        return None
                    raise

            # If unique constraints are provided and lookup_field is not part of them,
            # search by unique constraints directly (enables rename operations)
            if unique_constraints and self.lookup_field not in unique_constraints:
                results = api.get(**unique_constraints)
                if len(results) == 1:
                    return results[0]
                if len(results) > 1:
                    self.module.fail_json(
                        msg=(f"Multiple {self.singular} resources found with " f"unique_constraints={unique_constraints}")
                    )
                # len(results) == 0: no resource matches, fall through to lookup_field search

            # Try lookup field-based lookup
            if lookup_value:
                results = api.get(**{self.lookup_field: lookup_value})

                # Apply unique constraint filtering if specified
                if unique_constraints and results:
                    matches = [r for r in results if all(self._get_field_value(r, k) == v for k, v in unique_constraints.items())]
                    if len(matches) == 1:
                        resource = matches[0]
                    elif len(matches) > 1:
                        self.module.fail_json(
                            msg=(
                                f"Multiple {self.singular} resources found with "
                                f"{self.lookup_field}='{lookup_value}' and unique_constraints={unique_constraints}"
                            )
                        )
                    else:
                        # len(matches) == 0: no resource matches the unique constraints
                        return None
                elif results:
                    # No constraints: use first result (backward compatible)
                    resource = results[0]
                else:
                    return None

                # Smart refetch: Only if user wants fields missing from list result
                if self._needs_detail_fetch(resource):
                    try:
                        return api[resource["id"]].first() or resource
                    except Exception:
                        # If detail fetch fails, return list result
                        return resource

                return resource

            return None
        except Exception as e:
            raise VastAPIError(
                f"Failed to get {self.singular} (lookup_field={self.lookup_field}, lookup_value={lookup_value}, id={resource_id}): {e}"
            ) from e

    def create(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Create a new resource.

        Args:
            payload: Resource data

        Returns:
            Created resource dict

        Raises:
            VastAPIError: On API errors
        """
        try:
            api = self.client.api[self.resource_name]
            result = api.post(**payload)
        except Exception as e:
            raise VastAPIError(f"Failed to create {self.singular}: {e}") from e

        # Wait for async create if needed
        if self.async_create and self.params.get("wait", True):
            self._wait_for_task(result)
            # Refresh to get actual resource data (not task object)
            if "id" in result and result.get("type") != "async_task":
                refreshed = self.get(resource_id=result["id"])
                if refreshed:
                    return refreshed

        return result

    def update(self, resource_id: int, patch: Dict[str, Any]) -> Dict[str, Any]:
        """Update an existing resource.

        Args:
            resource_id: Resource ID
            patch: Fields to update

        Returns:
            Updated resource dict

        Raises:
            VastAPIError: On API errors
        """
        try:
            api = self.client.api[self.resource_name]
            result = api[resource_id].patch(**patch)
        except Exception as e:
            raise VastAPIError(f"Failed to update {self.singular} {resource_id}: {e}") from e

        # Wait for async update if needed
        if self.async_update and self.params.get("wait", True):
            self._wait_for_task(result)
            # Refresh to get actual resource data (not task object)
            refreshed = self.get(resource_id=resource_id)
            if refreshed:
                return refreshed

        return result

    def delete(self, resource_id: int) -> Dict[str, Any]:
        """Delete a resource.

        Args:
            resource_id: Resource ID

        Returns:
            Delete response (may contain task_id for async)

        Raises:
            VastAPIError: On API errors
        """
        try:
            api = self.client.api[self.resource_name]
            result = api[resource_id].delete()
            result = result if result else {}
        except Exception as e:
            raise VastAPIError(f"Failed to delete {self.singular} {resource_id}: {e}") from e

        # Wait for async delete if needed
        if self.async_delete and self.params.get("wait", True):
            self._wait_for_task(result)

        return result

    def build_desired_state(self, operation: str = "update", current_state: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """Build desired state from module parameters.

        Excludes connection parameters, framework fields, and operation-specific fields.

        Args:
            operation: One of "create" or "update" - determines which fields to include
            current_state: Current resource state (for smart update_only_fields handling)

        Returns:
            Dict of resource fields from module parameters
        """
        # Exclude framework parameters (connection, state, wait, etc.)
        exclude_keys = {
            "vms",  # Connection parameters are nested in this dict
            "id",  # ID is for lookup only, not part of desired state
            "state",
            "wait",
            "wait_timeout",
            "query",
            # Special operation parameters (actions, not resource fields)
            "set_posix_primary",
            "revoke",
            "revoke_access_keys",
        }

        # Add operation-specific exclusions based on Swagger spec
        if operation == "create":
            # During create, exclude update-only fields (e.g., s3policies.enabled)
            # These fields cannot be set during creation per Swagger spec
            exclude_keys.update(self.update_only_fields)
        elif operation == "update":
            # During update, exclude create-only fields (can't be changed after creation)
            exclude_keys.update(self.create_only_fields)

        desired = {}
        for key, value in self.params.items():
            if key not in exclude_keys and value is not None:
                desired[key] = value

        return desired

    def validate_run_params(self) -> None:
        """Validate parameters before run().

        Ensures we have a way to identify the resource for state=present.
        Subclasses can override for custom validation (e.g. CnodeResource
        relaxes this for loopback clusters).

        Raises:
            VastAPIError: If required parameters are missing.
        """
        state = self.params.get("state", "present")
        lookup_value = self.params.get(self.lookup_field)
        resource_id = self.params.get("id")
        if not lookup_value and not resource_id and state == "present":
            raise VastAPIError(f"Either '{self.lookup_field}' or 'id' parameter is required when state=present")

    def run(self) -> None:
        """Main execution entry point.

        Wraps ``_run_lifecycle()`` so that any ``VastAPIError`` is caught,
        debug traces are emitted (on failure only), and ``fail_json`` is
        called exactly once at the boundary.
        """
        try:
            self._run_lifecycle()
        except VastAPIError as e:
            self._emit_debug_traces()
            self.module.fail_json(msg=str(e))

    def _run_lifecycle(self) -> None:
        """Full CRUD lifecycle -- called by ``run()``.

        All errors raise ``VastAPIError``; the caller handles ``fail_json``.
        """
        # Check for special operation parameters (BaseResource only supports CRUD operations)
        special_ops = {
            "set_posix_primary",
            "revoke",
            "revoke_access_keys",
        }
        active_special_ops = [op for op in special_ops if self.params.get(op)]

        if active_special_ops:
            if self.check_mode:
                self.module.exit_json(
                    changed=True,
                    msg=f"Check mode: Would perform special operation(s): {', '.join(active_special_ops)}",
                    **{self.resource_name: {}},
                )
            raise VastAPIError(
                f"Special operations ({', '.join(active_special_ops)}) require custom module implementation. "
                f"The BaseResource class only supports standard CRUD operations (create, read, update, delete)."
            )

        state = self.params.get("state", "present")
        lookup_value = self.params.get(self.lookup_field)
        resource_id = self.params.get("id")

        self.validate_run_params()

        # Build unique constraints dict from params for composite key lookups
        unique_constraint_fields = self.overrides.get("unique_constraints", set())
        unique_constraints = None
        if unique_constraint_fields:
            unique_constraints = {k: self.params.get(k) for k in unique_constraint_fields if self.params.get(k) is not None}
            if unique_constraints and lookup_value and self.lookup_field in unique_constraint_fields:
                if self.lookup_field not in unique_constraints:
                    unique_constraints[self.lookup_field] = lookup_value

        # Get current state
        current = (
            self.get(lookup_value, resource_id, unique_constraints=unique_constraints) if (lookup_value or resource_id) else None
        )

        changed = False
        result_data = {}
        diff_before = {}
        diff_after = {}

        if state == "absent":
            if current:
                if not self.check_mode:
                    self.delete(current["id"])
                changed = True
                diff_before = dict(current)
                diff_after = {}
            result_data = current or {}

        else:  # state == present
            desired = self.build_desired_state(operation="create" if not current else "update", current_state=current)

            if not current:
                if self.update_only_fields:
                    provided_update_only = [f for f in self.update_only_fields if f in self.params and self.params[f] is not None]
                    if provided_update_only:
                        self.module.warn(
                            f"Fields {provided_update_only} are update-only per API spec and will be ignored during creation. "
                            f"The resource will be created without these fields. "
                            f"To set them, run a separate update task after creation."
                        )
                if not self.check_mode:
                    result_data = self.create(desired)
                else:
                    result_data = desired
                changed = True
                diff_before = {}
                diff_after = dict(result_data)
            else:
                current_normalized = normalize_resource(current, self.overrides, exclude_immutable=True, user_resource=desired)
                desired_normalized = normalize_resource(
                    desired,
                    self.overrides,
                    exclude_immutable=True,
                    include_ephemeral=self.include_ephemeral_in_updates,
                )
                patch = compute_patch(current_normalized, desired_normalized, self.overrides)

                if patch:
                    if not self.check_mode:
                        result_data = self.update(current["id"], patch)
                    else:
                        result_data = {**current, **patch}
                    changed = True
                    diff_before = dict(current)
                    diff_after = dict(result_data)
                else:
                    result_data = current

        # Build result
        result = {
            "changed": changed,
            self.resource_name: result_data,
        }
        if changed and (diff_before or diff_after):
            result["diff"] = {"before": diff_before, "after": diff_after}

        self.module.exit_json(**result)

    def _wait_for_task(self, response: Dict[str, Any]) -> None:
        """Wait for an async task to complete.

        Args:
            response: API response that may contain task_id

        Raises:
            VastAPIError: If task fails or times out.
        """
        if response is None:
            return
        task_id = VastClient.extract_task_id(response)
        if task_id:
            try:
                self.client.wait_for_task(task_id, timeout=self.params.get("wait_timeout", DEFAULT_TASK_TIMEOUT))
            except VastAPIError as e:
                raise VastAPIError(f"Async task {task_id} failed: {str(e)}") from e
