#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: activedirectory
short_description: Create, update, or delete VAST ActiveDirectory resources
description:
  - Create, update, or delete VAST ActiveDirectory resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
      debug:
        description: Enable HTTP debug traces. Traces are emitted as warnings on failure.
        type: bool
        default: false
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  abac_read_only_value_name:
    description: "The attribute to use when querying a provider for a read only attribute access check"
    type: str

  abac_read_write_value_name:
    description: "The attribute to use when querying a provider for a read-write attribute access check"
    type: str

  admin_passwd:
    description: |
      The password for the specified Active Directory admin user. (Note: This field is not returned by the API and only
      used during operations)
    type: str

  admin_username:
    description: |
      An Active Directory admin user with permission to join the Active Directory server. (Note: This field is not
      returned by the API and only used during operations)
    type: str

  binddn:
    description: |
      The bind DN for authenticating to the LDAP domain. You can specify any user account that has read access to the
      domain.
    type: str

  bindpw:
    description: |
      The password used with the Bind DN to authenticate to the LDAP server. (Note: This field is not returned by the
      API and only used during operations)
    type: str

  domain_name:
    description: "FQDN of Active Directory domain. Must be resolvable in DNS"
    type: str

  domains_with_posix_attributes:
    description: |
      Allows to enumerate specific domains for POSIX attributes in case posix_attributes_source is set to
      SPECIFIC_DOMAINS.
    type: list
    elements: str

  enabled:
    description: "Set to true to join Active Directory. Set to false to leave Active Directory."
    type: bool

  gid_number:
    description: |
      Override 'gidNumber' as the attribute of a group entry that contains the group's GID number. When binding VAST
      Cluster to AD, you may need to set this to 'gidnumber' (case sensitive).
    type: str

  group_login_name:
    description: |
      The attribute used to query Active Directory for the group login name in NFS ID mapping. Applicable only with
      Active Directory and NFSv4.
    type: str

  group_searchbase:
    description: |
      Base DN for group queries within the joined domain only. When auto discovery is enabled, group queries outside
      the joined domain use auto-discovered Base DNs.
    type: str

  is_vms_auth_provider:
    description: |
      Enables use of the LDAP for VMS authentication. Two LDAP configurations per cluster can be used for VMS
      authentication: one with Active Directory and one without.
    type: bool

  machine_account_name:
    description: "The name for the machine object representing the VAST Cluster to be created within the OU."
    type: str

  mail_property_name:
    description: "Mail Property Name"
    type: str

  match_user:
    description: |
      The attribute to use when querying a provider for a user that matches a user that was already retrieved from
      another provider. A user entry that contains a matching value in this attribute will be considered the same user
      as the user previously retrieved.
    type: str

  method:
    description: "The authentication method configured on the LDAP server for authenticating clients."
    type: str
    choices: ["anonymous", "simple", "sasl", "krbv4", "krbv41", "krbv42"]

  monitor_action:
    description: |
      The type of periodic health check that VAST Cluster performs for the Active Directory provider. PING (default,
      less overhead and impact on the provider) = pings the provider. BIND = binds to the provider.
    type: str
    choices: ["PING", "BIND"]

  ntlm_enabled:
    description: "Manages support of NTLM authentication method for SMB protocol."
    type: bool

  organizational_unit:
    description: |
      A non default organizational unit (OU) in the Active Directory domain in which to create the machine object. If
      left empty, the machine object will be created in the default Computers OU.
    type: str

  port:
    description: "The port of the remote LDAP server. Typical values: 389, 636."
    type: int

  posix_account:
    description: |
      Override 'posixAccount'as the object class that defines a user entry on the LDAP server. When binding VAST
      Cluster to AD, set this parameter to 'user' in order for authorization to work properly.
    type: str

  posix_attributes_source:
    description: "Defines which domains POSIX attributes will be supported from."
    type: str
    choices: ["JOINED_DOMAIN", "ALL_DOMAINS", "SPECIFIC_DOMAINS", "GC"]

  posix_group:
    description: |
      Override 'posixGroup' as the object class that defines a group entry on the LDAP server. When binding VAST
      Cluster to AD, set this parameter to 'group' in order for authorization to work properly.
    type: str

  query_groups_mode:
    description: |
      A mode setting for how groups are queried: Set to COMPATIBLE to look up user groups using the 'memberOf' and
      'memberUid' attributes. Set to RFC2307BIS_ONLY to look up user groups using only the 'memberOf' attribute. Set to
      RFC2307_ONLY to look up user groups using only the 'memberUid' attribute. Set to NONE not to look up user groups
      other than by leading GID and primary group SID.
    type: str

  query_posix_attributes_from_gc:
    description: |
      When set to True - users/groups from non-joined domain POSIX attributes are supported, when set to False - Posix
      attributes of users/groups from non-joined domain are not supported. As a condition Global catalog needs to be
      configured to support Posix attributes. (deprecated since 4.6)
    type: bool

  reverse_lookup:
    description: "resolve netgroups into hostnames"
    type: bool

  scheduled_ma_pwd_change_enabled:
    description: "Enables scheduled Machine Account password change."
    type: bool

  searchbase:
    description: "The entry in the LDAP directory tree to use as a starting point for user queries."
    type: str

  smb_allowed:
    description: "Indicates if the Active Directory configuration is allowed to serve as a provider for SMB attributes."
    type: bool

  super_admin_groups:
    description: |
      List of groups on the Active Directory provider. Members of these groups can log into VMS as cluster admin users.
    type: list
    elements: str

  tls_certificate:
    description: "TLS certificate to use for verifying the remote LDAP server's TLS certificate."
    type: str

  uid:
    description: |
      Override 'uid' as the attribute of a user entry on the LDAP server that contains the user name. When binding VAST
      Cluster to AD, you may need to set this to 'sAMAccountname'.
    type: str

  uid_member:
    description: |
      Override 'memberUid' as the attribute of a group entry on the LDAP server that contains names of group members.
      When binding VAST Cluster to AD, you may need to set this to 'memberUID'
    type: str

  uid_member_value_property_name:
    description: "Uid Member Value Property Name"
    type: str

  uid_number:
    description: |
      Override 'uidNumber' as the attribute of a user entry on the LDAP server that contains the UID number. Often when
      binding VAST Cluster to Active Directory this does not need to be set.
    type: str

  urls:
    description: |
      Comma separated list of URIs of LDAP servers in the format <scheme>://<address>. The order of listing defines the
      priority order. The URI with highest priority that has a good health status is used.
    type: list
    elements: str

  use_auto_discovery:
    description: |
      When enabled, Active Directory Domain Controllers (DCs) and Active Directory domains are auto discovered. Queries
      extend beyond the joined domain to all domains in the forest. When disabled, queries are restricted to the joined
      domain and DCs must be provided in the URLs field.
    type: bool

  use_ldaps:
    description: "Use LDAPS for Auto-Discovery"
    type: bool

  use_multi_forest:
    description: "Allow access for users from trusted domains on other forests."
    type: bool

  use_posix:
    description: "POSIX support (Note: This field is not returned by the API and only used during operations)"
    type: bool

  use_tls:
    description: "Set to true to enable use of TLS to secure communication between VAST Cluster and the LDAP server."
    type: bool

  user_login_name:
    description: |
      The attribute used to query Active Directory for the user login name in NFS ID mapping. Applicable only with
      Active Directory and NFSv4.
    type: str

  username_property_name:
    description: |
      The attribute to use for querying users in VMS user-initated user queries. Default is 'name'. Sometimes set to
      'cn'
    type: str

  skip_ldap:
    description: |
      Set to true to avoid removing the LDAP server configuration that is attached to the Active Directory
      configuration. (only used when state=absent)
    type: bool
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create ActiveDirectory
  vastdata.vms.activedirectory:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    state: present

- name: Update ActiveDirectory
  vastdata.vms.activedirectory:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    machine_account_name: "example-value"
    state: present

- name: Delete ActiveDirectory
  vastdata.vms.activedirectory:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    machine_account_name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
activedirectory:
  description: The activedirectory resource data.
  type: dict
  returned: always
  sample:
    id: 1
    machine_account_name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "abac_read_only_value_name": {"type": "str", "default": None},
    "abac_read_write_value_name": {"type": "str", "default": None},
    "admin_passwd": {"type": "str", "default": None, "no_log": True},
    "admin_username": {"type": "str", "default": None},
    "binddn": {"type": "str", "default": None},
    "bindpw": {"type": "str", "default": None, "no_log": True},
    "domain_name": {"type": "str", "default": None},
    "domains_with_posix_attributes": {"type": "list", "default": None, "elements": "str"},
    "enabled": {"type": "bool", "default": None},
    "gid_number": {"type": "str", "default": None},
    "group_login_name": {"type": "str", "default": None},
    "group_searchbase": {"type": "str", "default": None},
    "is_vms_auth_provider": {"type": "bool", "default": None},
    "machine_account_name": {"type": "str", "default": None},
    "mail_property_name": {"type": "str", "default": None},
    "match_user": {"type": "str", "default": None},
    "method": {
        "type": "str",
        "default": None,
        "choices": [
            "anonymous",
            "simple",
            "sasl",
            "krbv4",
            "krbv41",
            "krbv42",
        ],
    },
    "monitor_action": {"type": "str", "default": None, "choices": ["PING", "BIND"]},
    "ntlm_enabled": {"type": "bool", "default": None},
    "organizational_unit": {"type": "str", "default": None},
    "port": {"type": "int", "default": None},
    "posix_account": {"type": "str", "default": None},
    "posix_attributes_source": {
        "type": "str",
        "default": None,
        "choices": [
            "JOINED_DOMAIN",
            "ALL_DOMAINS",
            "SPECIFIC_DOMAINS",
            "GC",
        ],
    },
    "posix_group": {"type": "str", "default": None},
    "query_groups_mode": {"type": "str", "default": None},
    "query_posix_attributes_from_gc": {"type": "bool", "default": None},
    "reverse_lookup": {"type": "bool", "default": None},
    "scheduled_ma_pwd_change_enabled": {"type": "bool", "default": None},
    "searchbase": {"type": "str", "default": None},
    "smb_allowed": {"type": "bool", "default": None},
    "super_admin_groups": {"type": "list", "default": None, "elements": "str"},
    "tls_certificate": {"type": "str", "default": None},
    "uid": {"type": "str", "default": None},
    "uid_member": {"type": "str", "default": None},
    "uid_member_value_property_name": {"type": "str", "default": None},
    "uid_number": {"type": "str", "default": None},
    "urls": {"type": "list", "default": None, "elements": "str"},
    "use_auto_discovery": {"type": "bool", "default": None},
    "use_ldaps": {"type": "bool", "default": None},
    "use_multi_forest": {"type": "bool", "default": None},
    "use_posix": {"type": "bool", "default": None},
    "use_tls": {"type": "bool", "default": None},
    "user_login_name": {"type": "str", "default": None},
    "username_property_name": {"type": "str", "default": None},
    "skip_ldap": {"type": "bool", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ActivedirectoryResource(BaseResource):
    """Resource manager for ActiveDirectory."""

    resource_name = "activedirectory"
    singular = "activedirectory"
    lookup_field = "machine_account_name"
    async_update = True
    create_only_fields = {
        "ldap_id",
        "machine_account_name",
        "organizational_unit",
        "preferred_dc_list",
    }  # Fields only valid during creation
    update_only_fields = {"admin_passwd", "admin_username", "enabled"}  # Fields only valid during updates
    delete_body_params = {"skip_ldap"}  # Sent in JSON body on DELETE


# END AUTOGENERATED RESOURCE_CLASS


def _apply_activedirectory_customizations():  # isort: skip
    """ActiveDirectory-specific overrides applied at import time.

    Wrapped in a function so ansible-doc's AST parser does not choke on
    subscript assignments or attribute patches at module level.
    """

    def _activedirectory_update(self, resource_id: int, patch: Dict[str, Any]) -> Dict[str, Any]:
        """Update Active Directory resource with special handling for join/leave operations.

        When 'enabled' is in the patch (join/leave operation), we must include
        admin_username and admin_passwd even though they're normally ephemeral fields.
        The API requires these credentials for join/leave operations.
        """
        if "enabled" in patch:
            missing = [f for f in ("admin_username", "admin_passwd") if self.params.get(f) is None]
            if missing:
                self.module.fail_json(
                    msg=(
                        "admin_username and admin_passwd are required for join/leave operations " f"(missing: {', '.join(missing)})"
                    )
                )
            for field in ("admin_username", "admin_passwd"):
                if field not in patch:
                    patch[field] = self.params[field]

        return BaseResource.update(self, resource_id, patch)

    ActivedirectoryResource.update = _activedirectory_update


_apply_activedirectory_customizations()


# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ActivedirectoryResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
