#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: apitokens
short_description: Create, or update VAST ApiToken resources
description:
  - Create, or update VAST ApiToken resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
      debug:
        description: Enable HTTP debug traces. Traces are emitted as warnings on failure.
        type: bool
        default: false
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: str
  expiry_date:
    description: |
      Changes the expiration date of the token. Specify the amount of time from token creation until the token should
      expire. The expiration date is equal to the token creation date in UTC + the specified time period. Specify as a
      whole integer followed by a unit of time: 'Y' for (365 day) years, 'M' for (30 day) months, 'w' or 'W' for weeks,
      'd' or 'D' for days, 'h' or 'H' for hours, 'm' for minutes, 's' or 'S' for seconds. The maximum and default
      expiration time is the password expiration timeout.
    type: str

  name:
    description: "Sets a new name for the token."
    type: str

  owner:
    description: |
      The user name of the user for whom to create the API token. If not specified, the token is created for the
      requesting user.
    type: str
  state:
    description: Desired state of the resource (absent is not supported).
    type: str
    choices: [present]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create ApiToken
  vastdata.vms.apitokens:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    state: present

- name: Update ApiToken
  vastdata.vms.apitokens:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
apitokens:
  description: The apitokens resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "str", "default": None},
    "expiry_date": {"type": "str", "default": None},
    "name": {"type": "str", "default": None},
    "owner": {"type": "str", "default": None},
    "state": {"type": "str", "choices": ["present"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ApitokenResource(BaseResource):
    """Resource manager for ApiToken."""

    resource_name = "apitokens"
    singular = "apitoken"
    lookup_field = "name"
    create_only_fields = {"owner"}  # Fields only valid during creation


# END AUTOGENERATED RESOURCE_CLASS


def _apply_apitokens_customizations():  # isort: skip
    """Apitokens-specific update override applied at import time.

    PATCH /apitokens/{id}/ returns a confirmation string (e.g.
    ``"apitoken updated"``) instead of the updated resource object, which
    breaks callers that expect ``update()`` to return a dict (``dict(result)``
    in the generic ``run()`` raises an opaque "dictionary update sequence"
    error). The override re-fetches the resource via GET when the PATCH
    response is not a dict, keeping the quirk localized to the one endpoint
    that exhibits it instead of penalising ``BaseResource.update`` for the
    entire collection.

    Wrapped in a function so ansible-doc's AST parser does not choke on
    attribute patches at module level.
    """
    from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastAPIError

    _base_update = ApitokenResource.update

    def _apitokens_update(self, resource_id, patch):
        result = _base_update(self, resource_id, patch)
        if isinstance(result, dict):
            return result
        refreshed = self.get(resource_id=resource_id)
        if refreshed is None:
            raise VastAPIError(f"apitoken {resource_id} update succeeded but the resource could not be re-fetched")
        return refreshed

    ApitokenResource.update = _apitokens_update


_apply_apitokens_customizations()


# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ApitokenResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
