#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: apitokens/revoke

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: apitoken_revoke
short_description: Manage apitoken revoke
description:
  - Manage apitoken revoke.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  apitoken_id:
    description: "ID of the apitoken"
    type: str
    required: true
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage apitoken revoke
  vastdata.vms.apitoken_revoke:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    apitoken_id: 1
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
result:
  description: The operation result.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "apitoken_id": {"required": True, "type": "str"},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class ApitokenRevoke(SubEndpointResource):
    parent_resource = "apitokens"
    sub_path = "revoke"
    path_has_id = True
    supported_operations = frozenset({CrudCapability.UPDATE})
    parent_id_param = "apitoken_id"
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS


def _apply_apitoken_revoke_customizations():
    """ApitokenRevoke-specific idempotency override applied at import time.

    The /apitokens/{id}/revoke/ endpoint has no read-side semantics of its
    own -- a second revoke returns the same 200 OK with the same body. To
    make this module idempotent we read the parent apitoken's `revoked`
    flag (which GET /apitokens/{id}/ returns even on revoked tokens) and
    short-circuit when it is already true.

    Wrapped in a function so ansible-doc's AST parser does not choke on
    attribute patches at module level.
    """
    from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastAPIError

    def _apitoken_revoke_run(self) -> None:
        apitoken_id = self.params[self.parent_id_param]
        parent_api = self.client.api[self.parent_resource][apitoken_id]

        try:
            current = parent_api.first() or {}
        except VastAPIError as e:
            self.module.fail_json(msg=f"Failed to read apitoken {apitoken_id}: {e}")

        if current.get("revoked") is True:
            self.module.exit_json(
                changed=False,
                result=f"apitoken {apitoken_id} already revoked",
            )

        if self.check_mode:
            self.module.exit_json(
                changed=True,
                result=f"apitoken {apitoken_id} would be revoked",
            )

        try:
            result = self._api_base.patch()
        except VastAPIError as e:
            self.module.fail_json(msg=str(e))

        self.module.exit_json(changed=True, result=result)

    ApitokenRevoke.run = _apitoken_revoke_run


_apply_apitoken_revoke_customizations()


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ApitokenRevoke(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
