#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: blobexpansions/drop_columns

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: blobexpansion_drop_columns
short_description: Manage blobexpansion drop columns
description:
  - Manage blobexpansion drop columns.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  arrow_schema:
    description: "Schema of the columns to drop"
    type: list
    elements: dict
    required: true

  database_name:
    description: "Kafka bucket name containing the source topic"
    type: str
    required: true

  remove_copy_source_column:
    description: "Remove copy of the raw source column from target table"
    type: bool

  remove_excessive_values_output:
    description: "Remove the excessive-values output column from the target table"
    type: bool

  remove_missing_values_output:
    description: "Remove the missing-values output column from the target table"
    type: bool

  source_column_name:
    description: "Source column name (defaults to \"value\" for Kafka topics)"
    type: str

  table_name:
    description: "Source Kafka topic name"
    type: str
    required: true

  tenant_id:
    description: "Tenant ID"
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage blobexpansion drop columns
  vastdata.vms.blobexpansion_drop_columns:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
result:
  description: The operation result.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "arrow_schema": {"type": "list", "required": True, "elements": "dict"},
    "database_name": {"type": "str", "required": True},
    "remove_copy_source_column": {"type": "bool", "default": None},
    "remove_excessive_values_output": {"type": "bool", "default": None},
    "remove_missing_values_output": {"type": "bool", "default": None},
    "source_column_name": {"type": "str", "default": None},
    "table_name": {"type": "str", "required": True},
    "tenant_id": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class BlobexpansionDropColumns(SubEndpointResource):
    parent_resource = "blobexpansions"
    sub_path = "drop_columns"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.UPDATE})
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # sub-endpoint introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = BlobexpansionDropColumns(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
