#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: blobexpansions/show

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: blobexpansion_show
short_description: Manage blobexpansion show
description:
  - Manage blobexpansion show.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  database_name:
    description: "Getting list of objects by database_name"
    type: str
    required: true

  source_column_name:
    description: "Source column name for blob expansion (defaults to \"value\" for Kafka topics)"
    type: str

  table_name:
    description: "Getting list of objects by table_name"
    type: str
    required: true

  tenant_id:
    description: "Filter by tenant. Specify tenant ID."
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage blobexpansion show
  vastdata.vms.blobexpansion_show:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
blobexpansion_show:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "database_name": {"type": "str", "required": True},
    "source_column_name": {"type": "str", "default": None},
    "table_name": {"type": "str", "required": True},
    "tenant_id": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class BlobexpansionShow(SubEndpointResource):
    parent_resource = "blobexpansions"
    sub_path = "show"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.READ})
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # sub-endpoint introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = BlobexpansionShow(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
