#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: callhomeconfigs_info
short_description: List VAST CallhomeConfig resources
description:
  - List VAST CallhomeConfig resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  aggregated:
    description: |
      If true, send aggregated callhome logs, otherwise upload logs from each node (deprecated) (optional filter)
    type: bool

  alt_s3_host_port:
    description: "Alternative S3 service host for upload. (optional filter)"
    type: str

  aws_s3_ak:
    description: "S3 Bucket access key (optional filter)"
    type: str

  aws_s3_bucket_name:
    description: "S3 Bucket for upload (optional filter)"
    type: str

  aws_s3_bucket_subdir:
    description: "Sub-Directory in support bucket (optional filter)"
    type: str

  aws_s3_sk:
    description: "S3 Bucket secret key (optional filter)"
    type: str

  bundle_enabled:
    description: "Enabled/disabled periodic bundle callhome (optional filter)"
    type: bool

  bundle_interval:
    description: "Interval in seconds for periodic bundle (optional filter)"
    type: int

  callhome_upload_destination:
    description: "Callhome upload destination (optional filter)"
    type: str
    choices: ["Matar", "Mars"]

  cloud_api_domain:
    description: "The domain name for the Cloud API (optional filter)"
    type: str

  cloud_api_key:
    description: "The API Key for the Cloud API (optional filter)"
    type: str

  cloud_enabled:
    description: "Is Cloud reporting modules enabled (optional filter)"
    type: bool

  cloud_registered:
    description: "Is the cluster registered with VAST Cloud Services (optional filter)"
    type: bool

  cloud_subdomain:
    description: "The Customer's subdomain in Vast Cloud Services (optional filter)"
    type: str

  compress_method:
    description: "Compression method for callhome bundles (by default zstd) (optional filter)"
    type: str

  customer:
    description: "Customer/Company name (optional filter)"
    type: str

  customer_id:
    description: "The id issued to the customer (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  location:
    description: "Site location (optional filter)"
    type: str

  log_enabled:
    description: "Enabled/disabled periodic log callhome (optional filter)"
    type: bool

  log_interval:
    description: "Interval in seconds for periodic log (optional filter)"
    type: int

  luna_analyze_period:
    description: "Analyzed period size, minutes (optional filter)"
    type: int

  luna_on_alarm_enabled:
    description: "Enabled/disabled luna analyzing tool on specific alarms (optional filter)"
    type: bool

  luna_on_alarm_interval:
    description: "Maximum allowed frequency in hours for alarm-triggered luna (optional filter)"
    type: int

  max_upload_bandwidth:
    description: "Maximum upload bandwidth in bytes (optional filter)"
    type: int

  max_upload_concurrency:
    description: "Maximum upload concurrency (optional filter)"
    type: int

  obfuscated:
    description: "If true, callhome data is obfuscated (optional filter)"
    type: bool

  proxy_host:
    description: "Proxy IP/hostname (optional filter)"
    type: str

  proxy_password:
    description: "Proxy password (optional filter)"
    type: str

  proxy_port:
    description: "Proxy Port (optional filter)"
    type: str

  proxy_scheme:
    description: "http, https, socks5, socks5h (optional filter)"
    type: str

  proxy_username:
    description: "Proxy username (optional filter)"
    type: str

  site:
    description: "Site name (optional filter)"
    type: str

  ssl_certificate:
    description: |
      SSL Certificate file content, including the BEGIN CERTIFICATE and END CERTIFICATE lines (optional filter)
    type: str

  support_channel:
    description: "Enable/disable the VAST support channel (optional filter)"
    type: bool

  test_mode:
    description: "enable/disable test mode (optional filter)"
    type: bool

  upload_via_vms:
    description: |
      If true, upload non-aggregated Callhome Bundle via VMS. Otherwise, upload from each node. (optional filter)
    type: bool

  verify_ssl:
    description: "Enable/disable ssl certificate verification (optional filter)"
    type: bool
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all callhomeconfigs
  vastdata.vms.callhomeconfigs_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: callhomeconfigs_result

- name: List callhomeconfigs filtered by id
  vastdata.vms.callhomeconfigs_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    id: example-value
  register: filtered_callhomeconfigs
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
callhomeconfigs:
  description: List of matching callhomeconfigs resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "aggregated": {"type": "bool", "default": None},
    "alt_s3_host_port": {"type": "str", "default": None},
    "aws_s3_ak": {"type": "str", "default": None, "no_log": True},
    "aws_s3_bucket_name": {"type": "str", "default": None},
    "aws_s3_bucket_subdir": {"type": "str", "default": None},
    "aws_s3_sk": {"type": "str", "default": None, "no_log": True},
    "bundle_enabled": {"type": "bool", "default": None},
    "bundle_interval": {"type": "int", "default": None},
    "callhome_upload_destination": {"type": "str", "default": None, "choices": ["Matar", "Mars"]},
    "cloud_api_domain": {"type": "str", "default": None},
    "cloud_api_key": {"type": "str", "default": None, "no_log": True},
    "cloud_enabled": {"type": "bool", "default": None},
    "cloud_registered": {"type": "bool", "default": None},
    "cloud_subdomain": {"type": "str", "default": None},
    "compress_method": {"type": "str", "default": None},
    "customer": {"type": "str", "default": None},
    "customer_id": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "location": {"type": "str", "default": None},
    "log_enabled": {"type": "bool", "default": None},
    "log_interval": {"type": "int", "default": None},
    "luna_analyze_period": {"type": "int", "default": None},
    "luna_on_alarm_enabled": {"type": "bool", "default": None},
    "luna_on_alarm_interval": {"type": "int", "default": None},
    "max_upload_bandwidth": {"type": "int", "default": None},
    "max_upload_concurrency": {"type": "int", "default": None},
    "obfuscated": {"type": "bool", "default": None},
    "proxy_host": {"type": "str", "default": None},
    "proxy_password": {"type": "str", "default": None, "no_log": True},
    "proxy_port": {"type": "str", "default": None},
    "proxy_scheme": {"type": "str", "default": None},
    "proxy_username": {"type": "str", "default": None},
    "site": {"type": "str", "default": None},
    "ssl_certificate": {"type": "str", "default": None, "no_log": True},
    "support_channel": {"type": "bool", "default": None},
    "test_mode": {"type": "bool", "default": None},
    "upload_via_vms": {"type": "bool", "default": None},
    "verify_ssl": {"type": "bool", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class CallhomeconfigInfoResource(BaseInfoResource):
    """Read-only list manager for CallhomeConfig."""

    resource_name = "callhomeconfigs"
    return_key = "callhomeconfigs"
    filter_fields = {
        "aggregated",
        "alt_s3_host_port",
        "aws_s3_ak",
        "aws_s3_bucket_name",
        "aws_s3_bucket_subdir",
        "aws_s3_sk",
        "bundle_enabled",
        "bundle_interval",
        "callhome_upload_destination",
        "cloud_api_domain",
        "cloud_api_key",
        "cloud_enabled",
        "cloud_registered",
        "cloud_subdomain",
        "compress_method",
        "customer",
        "customer_id",
        "id",
        "location",
        "log_enabled",
        "log_interval",
        "luna_analyze_period",
        "luna_on_alarm_enabled",
        "luna_on_alarm_interval",
        "max_upload_bandwidth",
        "max_upload_concurrency",
        "obfuscated",
        "proxy_host",
        "proxy_password",
        "proxy_port",
        "proxy_scheme",
        "proxy_username",
        "site",
        "ssl_certificate",
        "support_channel",
        "test_mode",
        "upload_via_vms",
        "verify_ssl",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = CallhomeconfigInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
