#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: dns
short_description: Create, update, or delete VAST DNS resources
description:
  - Create, update, or delete VAST DNS resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
      debug:
        description: Enable HTTP debug traces. Traces are emitted as warnings on failure.
        type: bool
        default: false
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  bgp_config_id:
    description: "The ID of the BGP configuration to use to configure layer 3 connectivity"
    type: int

  cnode_ids:
    description: "To dedicate a specific group of CNodes to the DNS, list the IDs of the CNodes."
    type: list
    elements: int

  domain_suffix:
    description: |
      A suffix for domain names. Requests for domain names with this suffix are resolved to the VIPs configured on the
      cluster.
    type: str

  enable_l3:
    description: "Enable layer 3 connectivity"
    type: bool

  enabled:
    description: "Set to true to enable the DNS service"
    type: bool

  invalid_name_response:
    description: "Invalid Name Response"
    type: str

  invalid_type_response:
    description: "Invalid Type Response"
    type: str

  name:
    description: "Name"
    type: str

  net_type:
    description: "Net Type"
    type: str

  port:
    description: "Specifies a port for the DNS"
    type: int

  ttl:
    description: "Specifies the TTL value for the DNS."
    type: int

  vip:
    description: |
      A virtual IP to assign to the DNS service. DNS requests from your external DNS server must be delegated to this
      IP.
    type: str

  vip_gateway:
    description: |
      If the external DNS server doesn't reside on the same subnet as the DNS VIP, enter the IP of a gateway through
      which to connect to the DNS server.
    type: str

  vip_ipv6:
    description: "Assigns an IPv6 to the DNS service."
    type: str

  vip_ipv6_gateway:
    description: "Specifies a gateway IPv6 to external DNS server if on different subnet."
    type: str

  vip_ipv6_subnet_cidr:
    description: "Specifies the subnet, as a CIDR index, on which the DNS resides. [1..128]"
    type: int

  vip_subnet_cidr:
    description: "The subnet, in CIDR format, on which the DNS VIP resides."
    type: int

  vip_vlan:
    description: |
      If your external DNS server is only exposed to a specific VLAN, you can enter the VLAN here to enable
      communication with the DNS server.
    type: int
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create DNS
  vastdata.vms.dns:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    vip: "example-vip"
    state: present

- name: Update DNS
  vastdata.vms.dns:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete DNS
  vastdata.vms.dns:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
dns:
  description: The dns resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "bgp_config_id": {"type": "int", "default": None},
    "cnode_ids": {"type": "list", "default": None, "elements": "int"},
    "domain_suffix": {"type": "str", "default": None},
    "enable_l3": {"type": "bool", "default": None},
    "enabled": {"type": "bool", "default": None},
    "invalid_name_response": {"type": "str", "default": None},
    "invalid_type_response": {"type": "str", "default": None},
    "name": {"type": "str", "default": None},
    "net_type": {"type": "str", "default": None},
    "port": {"type": "int", "default": None},
    "ttl": {"type": "int", "default": None},
    "vip": {"type": "str", "default": None},
    "vip_gateway": {"type": "str", "default": None},
    "vip_ipv6": {"type": "str", "default": None},
    "vip_ipv6_gateway": {"type": "str", "default": None},
    "vip_ipv6_subnet_cidr": {"type": "int", "default": None},
    "vip_subnet_cidr": {"type": "int", "default": None},
    "vip_vlan": {"type": "int", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class DnsResource(BaseResource):
    """Resource manager for DNS."""

    resource_name = "dns"
    singular = "dns"
    lookup_field = "name"
    create_only_fields = {"enable_l3"}  # Fields only valid during creation


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = DnsResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
