#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: dns_info
short_description: List VAST DNS resources
description:
  - List VAST DNS resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  bgp_config_id:
    description: "The ID of the BGP configuration used for L3 connectivity (optional filter)"
    type: int

  domain_suffix:
    description: |
      Specifies a suffix to append to domain names of each VIP pool. The suffix should complete each domain name to
      form a valid FQDN for DNS requests to target. (optional filter)
    type: str

  enable_l3:
    description: "Enable L3 connectivity (optional filter)"
    type: bool

  enabled:
    description: "Filter by enabled (optional filter)"
    type: bool

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  invalid_name_response:
    description: "Filter by invalid name response (optional filter)"
    type: str

  invalid_type_response:
    description: "Filter by invalid type response (optional filter)"
    type: str

  name:
    description: "Specifies a name for the VAST DNS server configuration (optional filter)"
    type: str

  net_type:
    description: "Filter by net type (optional filter)"
    type: str

  port:
    description: "Specifies a port for the DNS (optional filter)"
    type: int

  sync:
    description: "Synchronization state with leader (optional filter)"
    type: str

  sync_time:
    description: "Synchronization time with leader (optional filter)"
    type: str

  title:
    description: "Filter by title (optional filter)"
    type: str

  ttl:
    description: "Specifies the TTL value for the DNS. (optional filter)"
    type: int

  url:
    description: "Endpoint URL for operations on the DNS server configuration (optional filter)"
    type: str

  vip:
    description: |
      Assigns an IP to the DNS service. DNS requests from your external DNS server must be delegated to this IP.
      (optional filter)
    type: str

  vip_allocation:
    description: "VIP allocation type (optional filter)"
    type: str

  vip_gateway:
    description: |
      Specifies a gateway IP to external DNS server if on different subnet. Must be on same subnet as the IP and
      reachable from the relevant nework interface. (optional filter)
    type: str

  vip_ipv6:
    description: "Assigns an IPv6 to the DNS service. (optional filter)"
    type: str

  vip_ipv6_gateway:
    description: "Specifies a gateway IPv6 to external DNS server if on different subnet. (optional filter)"
    type: str

  vip_ipv6_subnet_cidr:
    description: "Specifies the subnet, as a CIDR index, on which the DNS resides. [1..128] (optional filter)"
    type: int

  vip_subnet_cidr:
    description: "Specifies the subnet, as a CIDR index, on which the DNS resides. (optional filter)"
    type: int

  vip_vlan:
    description: "Specifies a VLAN if needed to enable communication with external DNS server(s). (optional filter)"
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all dns
  vastdata.vms.dns_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: dns_result

- name: List dns filtered by name
  vastdata.vms.dns_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_dns
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
dns:
  description: List of matching dns resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "bgp_config_id": {"type": "int", "default": None},
    "domain_suffix": {"type": "str", "default": None},
    "enable_l3": {"type": "bool", "default": None},
    "enabled": {"type": "bool", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "invalid_name_response": {"type": "str", "default": None},
    "invalid_type_response": {"type": "str", "default": None},
    "name": {"type": "str", "default": None},
    "net_type": {"type": "str", "default": None},
    "port": {"type": "int", "default": None},
    "sync": {"type": "str", "default": None},
    "sync_time": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "ttl": {"type": "int", "default": None},
    "url": {"type": "str", "default": None},
    "vip": {"type": "str", "default": None},
    "vip_allocation": {"type": "str", "default": None},
    "vip_gateway": {"type": "str", "default": None},
    "vip_ipv6": {"type": "str", "default": None},
    "vip_ipv6_gateway": {"type": "str", "default": None},
    "vip_ipv6_subnet_cidr": {"type": "int", "default": None},
    "vip_subnet_cidr": {"type": "int", "default": None},
    "vip_vlan": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class DnsInfoResource(BaseInfoResource):
    """Read-only list manager for DNS."""

    resource_name = "dns"
    return_key = "dns"
    filter_fields = {
        "bgp_config_id",
        "domain_suffix",
        "enable_l3",
        "enabled",
        "guid",
        "id",
        "invalid_name_response",
        "invalid_type_response",
        "name",
        "net_type",
        "port",
        "sync",
        "sync_time",
        "title",
        "ttl",
        "url",
        "vip",
        "vip_allocation",
        "vip_gateway",
        "vip_ipv6",
        "vip_ipv6_gateway",
        "vip_ipv6_subnet_cidr",
        "vip_subnet_cidr",
        "vip_vlan",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = DnsInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
