#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: globalsnapstreams
short_description: Create, update, or delete VAST GlobalSnapStream resources
description:
  - Create, update, or delete VAST GlobalSnapStream resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  enabled:
    description: "Enabled"
    type: bool

  loanee_root_path:
    description: "ID of the path you want to clone. Specify only if cloning from a snapshot on the local cluster."
    type: str

  loanee_snapshot:
    description: "Loanee snapshot name"
    type: str

  loanee_snapshot_id:
    description: "ID of local snapshot to clone. Specify only if cloning from a snapshot on the local cluster."
    type: int

  loanee_tenant_id:
    description: "The target tenant for the clone, on the local cluster."
    type: int

  name:
    description: "Name"
    type: str

  owner_root_snapshot:
    description: |
      Details of the remote snapshot to clone. To retrieve details of snapshots per path, call
      /clusters/list_snapshoted_paths_remote/ and clusters/list_clone_snapshoted_paths_remote/. Specify only if cloning
      from remote.
    type: dict

  owner_tenant:
    description: "Owner tenant details"
    type: dict

  remote_target:
    description: |
      The name of a remote replication peer from which to clone a snapshot. Specify only if cloning from remote.
    type: str

  remote_target_id:
    description: |
      The ID of the remote replication peer from which to clone a snapshot. Specify only if cloning from remote.
    type: int

  status:
    description: "Status"
    type: dict

  view_replication_enabled:
    description: "Enables view replication Requires VMS 5.5 or later."
    type: bool

  remove_dir:
    description: "Remove Directory (only used when state=absent)"
    type: bool

  stop:
    description: Perform stop operation.
    type: bool
    default: false
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create GlobalSnapStream
  vastdata.vms.globalsnapstreams:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    state: present

- name: Update GlobalSnapStream
  vastdata.vms.globalsnapstreams:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete GlobalSnapStream
  vastdata.vms.globalsnapstreams:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
globalsnapstreams:
  description: The globalsnapstreams resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "enabled": {"type": "bool", "default": None},
    "loanee_root_path": {"type": "str", "default": None},
    "loanee_snapshot": {"type": "str", "default": None},
    "loanee_snapshot_id": {"type": "int", "default": None},
    "loanee_tenant_id": {"type": "int", "default": None},
    "name": {"type": "str", "default": None},
    "owner_root_snapshot": {"type": "dict", "default": None},
    "owner_tenant": {"type": "dict", "default": None},
    "remote_target": {"type": "str", "default": None},
    "remote_target_id": {"type": "int", "default": None},
    "status": {"type": "dict", "default": None},
    "view_replication_enabled": {"type": "bool", "default": None},
    "remove_dir": {"type": "bool", "default": None},
    "stop": {"type": "bool", "default": False},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class GlobalsnapstreamResource(BaseResource):
    """Resource manager for GlobalSnapStream."""

    resource_name = "globalsnapstreams"
    singular = "globalsnapstream"
    lookup_field = "name"
    async_create = True
    async_delete = True
    create_only_fields = {
        "guid",
        "id",
        "loanee_root_path",
        "loanee_snapshot",
        "loanee_snapshot_id",
        "loanee_tenant_id",
        "owner_root_snapshot",
        "owner_tenant",
        "remote_target",
        "remote_target_id",
        "status",
        "view_replication_enabled",
    }  # Fields only valid during creation
    delete_body_params = {"remove_dir"}  # Sent in JSON body on DELETE
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "guid": {"min": (5, 5), "max": None},
        "id": {"min": (5, 5), "max": None},
        "view_replication_enabled": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = GlobalsnapstreamResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
