#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: iamroles/credentials

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: iam_role_credentials
short_description: Query IAM role credentials
description:
  - Query IAM role credentials.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  iam_role_id:
    description: "ID of the IAM role"
    type: int
    required: true
  access_key:
    description: "Access key identifier whose STS credentials should be queried."
    type: str
    required: true
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Query IAM role credentials
  vastdata.vms.iam_role_credentials:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    iam_role_id: 1
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
iam_role_credentials:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "iam_role_id": {"required": True, "type": "int"},
    "access_key": {"type": "str", "required": True, "no_log": True},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class IamRoleCredentials(SubEndpointResource):
    parent_resource = "iamroles"
    sub_path = "credentials"
    path_has_id = True
    supported_operations = frozenset({CrudCapability.READ})
    parent_id_param = "iam_role_id"
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS


def _apply_iam_role_credentials_customizations():  # isort: skip
    """Forward required "access_key" query param on GET /iamroles/{id}/credentials/."""

    def _iam_role_credentials_get(self):
        try:
            return self._api_base.first(**self._build_payload()) or {}
        except VastError as e:
            self.module.fail_json(msg=f"Failed to read {self.sub_path}: {str(e)}")

    IamRoleCredentials.get = _iam_role_credentials_get


_apply_iam_role_credentials_customizations()


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = IamRoleCredentials(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
