#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: issues_info
short_description: List VAST Issue resources
description:
  - List VAST Issue resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  action:
    description: "Filter by action (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  issue:
    description: "Filter by issue (optional filter)"
    type: str

  issue_type:
    description: "Type of the issue (optional filter)"
    type: str

  location:
    description: "Issue location (optional filter)"
    type: str

  severity:
    description: "Filter by severity (optional filter)"
    type: str

  stage:
    description: "Issue stage (optional filter)"
    type: str

  task_id:
    description: "ID of a task (optional filter)"
    type: int

  time:
    description: "Filter by time (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all issues
  vastdata.vms.issues_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: issues_result

- name: List issues filtered by id
  vastdata.vms.issues_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    id: example-value
  register: filtered_issues
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
issues:
  description: List of matching issues resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "action": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "issue": {"type": "str", "default": None},
    "issue_type": {"type": "str", "default": None},
    "location": {"type": "str", "default": None},
    "severity": {"type": "str", "default": None},
    "stage": {"type": "str", "default": None},
    "task_id": {"type": "int", "default": None},
    "time": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class IssueInfoResource(BaseInfoResource):
    """Read-only list manager for Issue."""

    resource_name = "issues"
    return_key = "issues"
    filter_fields = {"action", "id", "issue", "issue_type", "location", "severity", "stage", "task_id", "time"}
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # resource introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = IssueInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
