#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: managers
short_description: Create, update, or delete VAST Manager resources
description:
  - Create, update, or delete VAST Manager resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
      debug:
        description: Enable HTTP debug traces. Traces are emitted as warnings on failure.
        type: bool
        default: false
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  first_name:
    description: "Manager's first name"
    type: str

  is_temporary_password:
    description: |
      The password is temporary. Expiration of temporary passwords is controlled by the tmp_pwd_expiration_timeout
      setting, which you can modify and retrieve through the /vms/{id}/pwd_settings/ path.
    type: bool

  last_name:
    description: "Manager's last name"
    type: str

  object_id:
    description: "object ID"
    type: int

  object_type:
    description: "object type"
    type: str

  password:
    description: "Manager's password (Note: This field is not returned by the API and only used during operations)"
    type: str

  password_expiration_disabled:
    description: "Password expiration is disabled"
    type: bool

  permissions:
    description: "permission type"
    type: str

  permissions_list:
    description: |
      Specify permissions list as an array of permission codenames in the format PERMISSION-REALM. To list permission
      codenames, run /permissions/get.
    type: list
    elements: str

  realm:
    description: "Realm type"
    type: str

  roles:
    description: "Specify all role IDs to update the roles assigned to the manager"
    type: list
    elements: int

  tenant_id:
    description: "Tenant ID. If user_type is TENANT_ADMIN, specify the ID of the tenant to which to grant admin access."
    type: int

  user_type:
    description: |
      Manager user type. SUPER_ADMIN aka 'cluster admin' = VMS manager users who can log into the cluster VMS to manage
      the cluster. TENANT_ADMIN=VMS manager users who can log into a specific tenant's VMS to manage that tenant.
    type: str
    choices: ["SUPER_ADMIN", "TENANT_ADMIN"]

  username:
    description: "Manager's user name"
    type: str
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create Manager
  vastdata.vms.managers:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    username: "example-username"
    password: "example-password"
    roles: []
    state: present

- name: Update Manager
  vastdata.vms.managers:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    username: "example-value"
    state: present

- name: Delete Manager
  vastdata.vms.managers:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    username: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
managers:
  description: The managers resource data.
  type: dict
  returned: always
  sample:
    id: 1
    username: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "first_name": {"type": "str", "default": None},
    "is_temporary_password": {"type": "bool", "default": None, "no_log": True},
    "last_name": {"type": "str", "default": None},
    "object_id": {"type": "int", "default": None},
    "object_type": {"type": "str", "default": None},
    "password": {"type": "str", "default": None, "no_log": True},
    "password_expiration_disabled": {"type": "bool", "default": None, "no_log": True},
    "permissions": {"type": "str", "default": None},
    "permissions_list": {"type": "list", "default": None, "elements": "str"},
    "realm": {"type": "str", "default": None},
    "roles": {"type": "list", "default": None, "elements": "int"},
    "tenant_id": {"type": "int", "default": None},
    "user_type": {"type": "str", "default": None, "choices": ["SUPER_ADMIN", "TENANT_ADMIN"]},
    "username": {"type": "str", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ManagerResource(BaseResource):
    """Resource manager for Manager."""

    resource_name = "managers"
    singular = "manager"
    lookup_field = "username"
    create_only_fields = {"tenant_id"}  # Fields only valid during creation
    update_only_fields = {"object_id", "object_type", "permissions", "realm"}  # Fields only valid during updates


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ManagerResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
