#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
#
# Sub-endpoint module: managers/authorized_status

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: manager_authorized_status
short_description: Query manager authorized status
description:
  - Query manager authorized status.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
      debug:
        description: Enable HTTP debug traces. Traces are emitted as warnings on failure.
        type: bool
        default: false
  action:
    description: |
      S3 / tabular / block / kafka action being probed (e.g. GetObject, PutObject, DeleteObject, ListBuckets,
      CreateBucket). The full set of accepted values is defined by the cluster's S3PermissionAction enum and may grow
      across versions.
    type: str
    required: true

  bucket_name:
    description: "Name of the S3 bucket the probed action would target."
    type: str
    required: true

  leading_vid:
    description: "Leading VID of the principal (e.g. user) being checked."
    type: int
    required: true

  object_path:
    description: "Path of the object within the bucket the probed action would target."
    type: str
    required: true

  owner_vid:
    description: "VID of the object owner."
    type: int
    required: true

  tenant_id:
    description: "Tenant ID under which the authorization probe is evaluated."
    type: int
    required: true
author:
  - VAST Data (@vastdata)
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Query manager authorized status
  vastdata.vms.manager_authorized_status:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
manager_authorized_status:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "action": {"type": "str", "required": True},
    "bucket_name": {"type": "str", "required": True},
    "leading_vid": {"type": "int", "required": True},
    "object_path": {"type": "str", "required": True},
    "owner_vid": {"type": "int", "required": True},
    "tenant_id": {"type": "int", "required": True},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class ManagerAuthorizedStatus(SubEndpointResource):
    parent_resource = "managers"
    sub_path = "authorized_status"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.READ})


# END AUTOGENERATED RESOURCE_CLASS


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ManagerAuthorizedStatus(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
