#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: nis_info
short_description: List VAST NIS resources
description:
  - List VAST NIS resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  domain_name:
    description: "The NIS domain name shared by all the NIS servers and clients on the network. (optional filter)"
    type: str

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  name:
    description: "Name of the NIS configuration (optional filter)"
    type: str

  posix_primary_provider:
    description: "POSIX primary provider (optional filter)"
    type: bool

  state:
    description: "Nis state (optional filter)"
    type: str
    choices: ["UNKNOWN", "FAILED", "CONNECTED"]

  tenant_id:
    description: "Filter by tenant id (optional filter)"
    type: int

  title:
    description: "Filter by title (optional filter)"
    type: str

  url:
    description: "Filter by url (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all nis
  vastdata.vms.nis_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: nis_result

- name: List nis filtered by name
  vastdata.vms.nis_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_nis
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
nis:
  description: List of matching nis resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "domain_name": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "name": {"type": "str", "default": None},
    "posix_primary_provider": {"type": "bool", "default": None},
    "state": {"type": "str", "default": None, "choices": ["UNKNOWN", "FAILED", "CONNECTED"]},
    "tenant_id": {"type": "int", "default": None},
    "title": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class NisInfoResource(BaseInfoResource):
    """Read-only list manager for NIS."""

    resource_name = "nis"
    return_key = "nis"
    filter_fields = {"domain_name", "guid", "id", "name", "posix_primary_provider", "state", "tenant_id", "title", "url"}
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = NisInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
