#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: users/non_local_keys

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: nonlocal_user_key
short_description: Manage non-local user access keys
description:
  - Manage non-local user access keys.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  access_key:
    description: "The access key"
    type: str

  enabled:
    description: "Set to true to enable the S3 access key pair. Set to false to disable the S3 access key pair."
    type: bool

  login_name:
    description: "User login name"
    type: str

  sid:
    description: "User SID. Required if UID is not provided"
    type: str

  tenant_id:
    description: "Tenant ID"
    type: int

  uid:
    description: "NFS UID. Required if SID is not provided"
    type: int

  username:
    description: "Username"
    type: str
  state:
    description: Desired state.
    type: str
    choices: [present, absent]
    default: present
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage non-local user access keys
  vastdata.vms.nonlocal_user_key:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
result:
  description: The operation result.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "access_key": {"type": "str", "default": None, "no_log": True},
    "enabled": {"type": "bool", "default": None},
    "login_name": {"type": "str", "default": None},
    "sid": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "uid": {"type": "int", "default": None},
    "username": {"type": "str", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class NonlocalUserKey(SubEndpointResource):
    parent_resource = "users"
    sub_path = "non_local_keys"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.CREATE, CrudCapability.DELETE, CrudCapability.UPDATE})
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS


def _apply_nonlocal_user_key_customizations():  # isort: skip
    """NonlocalUserKey-specific overrides applied at import time.

    The /users/non_local_keys/ endpoint has no GET; current key state is
    fetched via /users/query/ (returns the user with its access_keys list)
    so PATCH/DELETE can be idempotent. Without this override the framework's
    default _run_action always POSTs (CREATE+UPDATE both declared) and
    delete() drops the request body.
    """
    from typing import Any, Dict, Optional

    from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastAPIError, VastNotFoundError

    NonlocalUserKey.module_result_key = "result"
    NonlocalUserKey.identity_params = ["access_key"]
    # Fields that identify the user (used to scope user/key lookup); not part
    # of the PATCH/DELETE diff.
    _USER_IDENTITY = ("uid", "sid", "username", "login_name", "tenant_id")
    _DELETE_FIELDS = ("access_key", "uid", "sid", "tenant_id")

    def _build_user_identity(self) -> Dict[str, Any]:
        return {k: self.params[k] for k in _USER_IDENTITY if self.params.get(k) is not None}

    def _build_delete_payload(self) -> Dict[str, Any]:
        return {k: self.params[k] for k in _DELETE_FIELDS if self.params.get(k) is not None}

    def _get_current_key(self) -> Optional[Dict[str, Any]]:
        """Look up the current access_key entry by querying the non-local user."""
        access_key = self.params.get("access_key")
        if not access_key:
            return None
        identity = self._build_user_identity()
        if not identity:
            return None
        try:
            results = self.client.api["users"]["query"].get(**identity)
        except VastNotFoundError:
            return None
        except VastAPIError as e:
            self.module.warn(f"Could not query non-local user: {e}")
            return None
        if isinstance(results, dict):
            results = [results] if results else []
        if not results:
            return None
        for k in results[0].get("access_keys", []) or []:
            if k.get("access_key") == access_key:
                return k
        return None

    def _perform_update(self, current: Dict[str, Any]) -> None:
        payload = self._build_payload()
        changed = False
        for key, value in payload.items():
            if key in self.identity_params or key in _USER_IDENTITY:
                continue
            if current.get(key) != value:
                changed = True
                break
        if not changed:
            self.module.exit_json(changed=False, result=current)

        diff_before = dict(current)
        if self.check_mode:
            diff_after = {**current, **payload}
            self.module.exit_json(changed=True, result=diff_after, diff={"before": diff_before, "after": diff_after})

        try:
            self.update(payload)
        except VastAPIError as e:
            self.module.fail_json(msg=str(e))
        refreshed = self._get_current_key() or {**current, **{k: v for k, v in payload.items() if k not in _USER_IDENTITY}}
        self.module.exit_json(changed=True, result=refreshed, diff={"before": diff_before, "after": dict(refreshed)})

    def _perform_create(self) -> None:
        payload = self._build_payload()
        if self.check_mode:
            self.module.exit_json(changed=True, result=payload)
        try:
            result = self.create(payload)
        except VastAPIError as e:
            self.module.fail_json(msg=str(e))
        self.module.exit_json(changed=True, result=result)

    def _nonlocal_user_key_run(self) -> None:
        state = self.params.get("state", "present")

        if state == "absent":
            current = self._get_current_key()
            if current is None and self.params.get("access_key"):
                self.module.exit_json(changed=False, result={})
            if self.check_mode:
                self.module.exit_json(changed=True, result={})
            try:
                self._api_base.delete(**self._build_delete_payload())
            except VastNotFoundError:
                self.module.exit_json(changed=False, result={})
            except VastAPIError as e:
                self.module.fail_json(msg=f"Failed to delete {self.sub_path}: {e}")
            self.module.exit_json(changed=True, result={})

        access_key = self.params.get("access_key")
        if access_key:
            current = self._get_current_key()
            if current:
                self._perform_update(current)
                return
            self.module.fail_json(
                msg=(
                    f"access_key={access_key!r} not found for the given user/tenant. "
                    "Omit access_key to generate a new key, or pass an existing one to PATCH."
                )
            )

        self._perform_create()

    NonlocalUserKey._build_user_identity = _build_user_identity
    NonlocalUserKey._build_delete_payload = _build_delete_payload
    NonlocalUserKey._get_current_key = _get_current_key
    NonlocalUserKey._perform_update = _perform_update
    NonlocalUserKey._perform_create = _perform_create
    NonlocalUserKey.run = _nonlocal_user_key_run


_apply_nonlocal_user_key_customizations()


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = NonlocalUserKey(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
