#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: nonlocal_user_info
short_description: Manage non-local user query data
description:
  - Manage non-local user query data.
  - Read-only; always runs in check_mode and never reports changed.
version_added: "1.0.0"
options:
  allow_create_bucket:
    description: "Filter by allow create bucket (optional filter)"
    type: bool

  allow_delete_bucket:
    description: "Filter by allow delete bucket (optional filter)"
    type: bool

  group_count:
    description: "Filter by group count (optional filter)"
    type: int

  leading_group_gid:
    description: "Filter by leading group gid (optional filter)"
    type: int

  leading_group_name:
    description: "Filter by leading group name (optional filter)"
    type: str

  login_name:
    description: "Filter by login name (optional filter)"
    type: str

  name:
    description: "Filter by name (optional filter)"
    type: str

  object_type:
    description: "Filter by object type (optional filter)"
    type: str

  primary_group_name:
    description: "Filter by primary group name (optional filter)"
    type: str

  primary_group_sid:
    description: "Filter by primary group sid (optional filter)"
    type: str

  s3_connections_count:
    description: "Filter by s3 connections count (optional filter)"
    type: int

  s3_superuser:
    description: "Filter by s3 superuser (optional filter)"
    type: bool

  s3_vid:
    description: "Filter by s3 vid (optional filter)"
    type: int

  sid:
    description: "Filter by sid (optional filter)"
    type: str

  uid:
    description: "Filter by uid (optional filter)"
    type: int

  vid:
    description: "Filter by vid (optional filter)"
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List nonlocal_user
  vastdata.vms.nonlocal_user_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: nonlocal_user_result
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
nonlocal_user:
  description: List of matching sub-resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import SubEndpointInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "allow_create_bucket": {"type": "bool", "default": None},
    "allow_delete_bucket": {"type": "bool", "default": None},
    "group_count": {"type": "int", "default": None},
    "leading_group_gid": {"type": "int", "default": None},
    "leading_group_name": {"type": "str", "default": None},
    "login_name": {"type": "str", "default": None},
    "name": {"type": "str", "default": None},
    "object_type": {"type": "str", "default": None},
    "primary_group_name": {"type": "str", "default": None},
    "primary_group_sid": {"type": "str", "default": None},
    "s3_connections_count": {"type": "int", "default": None},
    "s3_superuser": {"type": "bool", "default": None},
    "s3_vid": {"type": "int", "default": None},
    "sid": {"type": "str", "default": None},
    "uid": {"type": "int", "default": None},
    "vid": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class NonlocalUserInfo(SubEndpointInfoResource):
    parent_resource = "users"
    sub_path = "query"
    path_has_id = False
    return_key = "nonlocal_user"
    filter_fields = {
        "allow_create_bucket",
        "allow_delete_bucket",
        "group_count",
        "leading_group_gid",
        "leading_group_name",
        "login_name",
        "name",
        "object_type",
        "primary_group_name",
        "primary_group_sid",
        "s3_connections_count",
        "s3_superuser",
        "s3_vid",
        "sid",
        "uid",
        "vid",
    }
    generated_min_version = (5, 4)


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = NonlocalUserInfo(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
