#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: users/query

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: nonlocal_user
short_description: Manage non-local user query data
description:
  - Manage non-local user query data.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  allow_create_bucket:
    description: |
      Set to true to give the user permission to create S3 buckets. In case of conflict with an S3 identity policy
      attached to the user or to a relevant group, this setting is overridden.
    type: bool

  allow_delete_bucket:
    description: |
      Set to true to give the user permission to delete S3 buckets. In case of conflict with an S3 identity policy
      attached to the user or to a relevant group, this setting is overridden.
    type: bool

  login_name:
    description: "Login name"
    type: str

  s3_policies_ids:
    description: "Specify S3 policies to attach to the user."
    type: list
    elements: int

  s3_superuser:
    description: |
      Set to true for S3 superuser. In case of conflict with an S3 identity policy attached to the user or to a
      relevant group, this setting is overridden.
    type: bool

  sid:
    description: "User SID"
    type: str

  tenant_id:
    description: "Tenant ID"
    type: int

  uid:
    description: "User UID"
    type: int

  username:
    description: "User legal name"
    type: str
  state:
    description: Desired state.
    type: str
    choices: [present, absent]
    default: present
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage non-local user query data
  vastdata.vms.nonlocal_user:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
nonlocal_user:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "allow_create_bucket": {"type": "bool", "default": None},
    "allow_delete_bucket": {"type": "bool", "default": None},
    "login_name": {"type": "str", "default": None},
    "s3_policies_ids": {"type": "list", "default": None, "elements": "int"},
    "s3_superuser": {"type": "bool", "default": None},
    "sid": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "uid": {"type": "int", "default": None},
    "username": {"type": "str", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class NonlocalUser(SubEndpointResource):
    parent_resource = "users"
    sub_path = "query"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.READ, CrudCapability.UPDATE})
    identity_params = ["tenant_id", "username"]
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = NonlocalUser(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
