#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: nonlocal_group_info
short_description: Manage non-local group query data
description:
  - Manage non-local group query data.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  context:
    description: "The provider to query (optional filter)"
    type: str
    choices: ["local", "udb", "ad", "ldap", "nis", "aggregated"]

  gid:
    description: "Group GID (optional filter)"
    type: int

  groupname:
    description: "Groupname (optional filter)"
    type: str

  sid:
    description: "Group SID (optional filter)"
    type: str

  tenant_id:
    description: "Filter by tenant. Specify tenant ID. (optional filter)"
    type: int

  vaid:
    description: "Group VAID (a VAST identifier for groups) (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List nonlocal_group
  vastdata.vms.nonlocal_group_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: nonlocal_group_result
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
nonlocal_group:
  description: List of matching sub-resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import SubEndpointInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "context": {"type": "str", "default": None, "choices": ["local", "udb", "ad", "ldap", "nis", "aggregated"]},
    "gid": {"type": "int", "default": None},
    "groupname": {"type": "str", "default": None},
    "sid": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "vaid": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class NonlocalGroupInfo(SubEndpointInfoResource):
    parent_resource = "groups"
    sub_path = "query"
    path_has_id = False
    return_key = "nonlocal_group"
    filter_fields = {"context", "gid", "groupname", "sid", "tenant_id", "vaid"}
    generated_min_version = (5, 4)


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = NonlocalGroupInfo(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
