#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: oidcs_info
short_description: List VAST OIDC resources
description:
  - List VAST OIDC resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  assigned_tenants_preview:
    description: "Filter by assigned tenants preview (optional filter)"
    type: str

  certificate:
    description: "Filter by certificate (optional filter)"
    type: str

  discovery_url:
    description: "Filter by discovery url (optional filter)"
    type: str

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  last_keys_refresh_time:
    description: "Filter by last keys refresh time (optional filter)"
    type: str

  name:
    description: "Filter by name (optional filter)"
    type: str

  state:
    description: "Filter by state (optional filter)"
    type: str

  user_jwt_attribute:
    description: "Filter by user jwt attribute (optional filter)"
    type: str

  verify_peer:
    description: "Filter by verify peer (optional filter)"
    type: bool
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all oidcs
  vastdata.vms.oidcs_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: oidcs_result

- name: List oidcs filtered by name
  vastdata.vms.oidcs_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_oidcs
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
oidcs:
  description: List of matching oidcs resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "assigned_tenants_preview": {"type": "str", "default": None},
    "certificate": {"type": "str", "default": None},
    "discovery_url": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "last_keys_refresh_time": {"type": "str", "default": None, "no_log": False},
    "name": {"type": "str", "default": None},
    "state": {"type": "str", "default": None},
    "user_jwt_attribute": {"type": "str", "default": None},
    "verify_peer": {"type": "bool", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class OidcInfoResource(BaseInfoResource):
    """Read-only list manager for OIDC."""

    resource_name = "oidcs"
    return_key = "oidcs"
    filter_fields = {
        "assigned_tenants_preview",
        "certificate",
        "discovery_url",
        "guid",
        "id",
        "last_keys_refresh_time",
        "name",
        "state",
        "user_jwt_attribute",
        "verify_peer",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = OidcInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
