#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: protectionpolicies
short_description: Create, update, or delete VAST ProtectionPolicy resources
description:
  - Create, update, or delete VAST ProtectionPolicy resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  big_catalog:
    description: "Indicates if Protection Policy will be used for VAST Catalog. There may only be 1 such policy."
    type: bool

  clone_type:
    description: |
      Specify the type of data protection. CLOUD_REPLICATION is S3 backup. LOCAL means local snapshots without
      replication.
    type: str
    choices: ["LOCAL", "NATIVE_REPLICATION", "CLOUD_REPLICATION"]

  frames:
    description: "Defines the schedule for snapshot creation and the local and remote retention policies."
    type: list
    elements: dict

  indestructible:
    description: |
      Set to true to protect the protection policy from accidental or malicious deletion with the indestructibility
      feature. If this setting is enabled, authorized unlocking of the cluster's indestructibility mechanism is
      required to do any of the following: modifying the policy, deleting the policy or disabling this setting.
    type: bool

  name:
    description: "Name"
    type: str

  prefix:
    description: "The prefix for names of snapshots created by the policy"
    type: str

  remote_tenant_guid:
    description: "remote tenant guid"
    type: str

  target_object_id:
    description: |
      ID of the remote peer. Specify ID of a ReplicationTarget (aka S3 replication peer) if clone_type is
      CLOUD_REPLICATION. Specify the ID of a NativeReplicationRemoteTarget if clone_type is NATIVE_REPLICATION.
    type: int

  tenant_id:
    description: "Tenant ID"
    type: int
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create ProtectionPolicy
  vastdata.vms.protectionpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-name"
    frames: []
    prefix: "example-prefix"
    clone_type: "LOCAL"
    state: present

- name: Update ProtectionPolicy
  vastdata.vms.protectionpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete ProtectionPolicy
  vastdata.vms.protectionpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
protectionpolicies:
  description: The protectionpolicies resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "big_catalog": {"type": "bool", "default": None},
    "clone_type": {
        "type": "str",
        "default": None,
        "choices": [
            "LOCAL",
            "NATIVE_REPLICATION",
            "CLOUD_REPLICATION",
        ],
    },
    "frames": {"type": "list", "default": None, "elements": "dict"},
    "indestructible": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "prefix": {"type": "str", "default": None},
    "remote_tenant_guid": {"type": "str", "default": None},
    "target_object_id": {"type": "int", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ProtectionpolicyResource(BaseResource):
    """Resource manager for ProtectionPolicy."""

    resource_name = "protectionpolicies"
    singular = "protectionpolicy"
    lookup_field = "name"
    create_only_fields = {"remote_tenant_guid", "tenant_id"}  # Fields only valid during creation
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "guid": {"min": (5, 5), "max": None},
        "id": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ProtectionpolicyResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
