#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: protectedpaths_info
short_description: List VAST ProtectedPath resources
description:
  - List VAST ProtectedPath resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  aggr_phys_estimation:
    description: "The usable capacity reclaimable by deleting all of its snapshots (optional filter)"
    type: int

  bucket_name:
    description: "Filter by bucket name (optional filter)"
    type: str

  bw:
    description: "Replication Bandwidth (optional filter)"
    type: int

  capabilities:
    description: |
      Indicates if the protected path supports global access streams or async replication streams or sync replication.
      (optional filter)
    type: str

  enabled:
    description: "start/pause replication (optional filter)"
    type: bool

  estimated_read_only_time:
    description: "Filter by estimated read only time (optional filter)"
    type: float

  eta:
    description: "Filter by eta (optional filter)"
    type: str

  failback_allowed:
    description: "Filter by failback allowed (optional filter)"
    type: str

  failover:
    description: "Trigger failover command (optional filter)"
    type: bool

  failure_reason:
    description: "Filter by failure reason (optional filter)"
    type: str

  guid:
    description: "guid (optional filter)"
    type: str

  health:
    description: "Filter by health (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  inode_count:
    description: "Filter by inode count (optional filter)"
    type: str

  internal:
    description: "Filter by internal (optional filter)"
    type: bool

  is_gn_enabled:
    description: "Indicates whether the Protected Path is enabled for Global Access (optional filter)"
    type: bool

  is_local:
    description: "Filter by is local (optional filter)"
    type: bool

  last_restore_point_creation_time:
    description: "Filter by last restore point creation time (optional filter)"
    type: str

  last_restore_point_time:
    description: "Filter by last restore point time (optional filter)"
    type: str

  last_snapshot_creation_time:
    description: "Filter by last snapshot creation time (optional filter)"
    type: str

  last_uploading_restore_point_logical_size:
    description: "Filter by last uploading restore point logical size (optional filter)"
    type: str

  last_uploading_restore_point_physical_size:
    description: "Filter by last uploading restore point physical size (optional filter)"
    type: str

  last_uploading_restore_point_progress:
    description: "Filter by last uploading restore point progress (optional filter)"
    type: int

  last_uploading_restore_point_state:
    description: "Filter by last uploading restore point state (optional filter)"
    type: str

  lease_expiry_time:
    description: |
      The lease expiry time, in seconds, for a global access protected path. This is the duration for which data that
      was already requested at the destination path can be read locally from cache without the destination peer
      requesting it from the source peer. When the lease expires, the cache is invalidated and the next read request
      for the data is requested again from the source peer. (optional filter)
    type: int

  logical_size:
    description: "Filter by logical size (optional filter)"
    type: int

  name:
    description: "Filter by name (optional filter)"
    type: str

  peer_cluster_name:
    description: "Filter by peer cluster name (optional filter)"
    type: str

  peer_connection_state:
    description: "Filter by peer connection state (optional filter)"
    type: str

  physical_size:
    description: "Filter by physical size (optional filter)"
    type: int

  progress:
    description: "Filter by progress (optional filter)"
    type: str

  protection_policy_id:
    description: "protection policy id (optional filter)"
    type: str

  protection_policy_name:
    description: "protection policy name (optional filter)"
    type: str

  remote_tenant_guid:
    description: "remote tenant guid (optional filter)"
    type: str

  remote_tenant_name:
    description: "remote tenant name (optional filter)"
    type: str

  replication_policy:
    description: "replication policy id (optional filter)"
    type: str

  replication_target_name:
    description: "Filter by replication target name (optional filter)"
    type: str

  restore_task:
    description: "link to restore task (optional filter)"
    type: str

  role:
    description: "current role in the replication (optional filter)"
    type: str

  role_change_eta_sec:
    description: "Filter by role change eta sec (optional filter)"
    type: int

  role_change_progress_promil:
    description: "Filter by role change progress promil (optional filter)"
    type: int

  source_dir:
    description: "path to replicate (optional filter)"
    type: str

  state:
    description: "state (optional filter)"
    type: str
    choices:
      - Failed
      - DELETED_ON_PEER
      - N/A
      - INVALID
      - DELETE_PENDING
      - Active
      - Suspended
      - Syncing
      - Finalizing
      - Initializing
      - Initial Scan
      - Initial Sync
      - Initial Sync Suspended
      - Writable
      - Blocked
      - Sync Failed
      - UNKNOWN
      - Calculating...
      - Local
      - Error
      - Degraded
      - INITIAL_SYNC
      - INCREMENTAL_SYNC
      - INCREMENTAL_SYNC_SUSPENDED
      - ERROR_DEPRECATED
      - LOCAL_ACTIVE
      - INITIAL_SCAN
      - DELETE_READY
      - INITIAL_SYNC_SUSPENDED
      - LOCAL_SUSPENDED
      - PENDING_SYNC
      - PENDING_CLEANUP

  state_description:
    description: "Filter by state description (optional filter)"
    type: str

  sync_disconnect_time:
    description: "Replication group sync replication disconnect time, in seconds (optional filter)"
    type: int

  sync_interval:
    description: "sync point assurance in seconds (optional filter)"
    type: int

  target_exported_dir:
    description: "where to replicate on the remote (optional filter)"
    type: str

  tenant_id:
    description: "Local Tenant ID (optional filter)"
    type: int

  tenant_name:
    description: "Local Tenant name (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all protectedpaths
  vastdata.vms.protectedpaths_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: protectedpaths_result

- name: List protectedpaths filtered by name
  vastdata.vms.protectedpaths_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_protectedpaths
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
protectedpaths:
  description: List of matching protectedpaths resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "aggr_phys_estimation": {"type": "int", "default": None},
    "bucket_name": {"type": "str", "default": None},
    "bw": {"type": "int", "default": None},
    "capabilities": {"type": "str", "default": None},
    "enabled": {"type": "bool", "default": None},
    "estimated_read_only_time": {"type": "float", "default": None},
    "eta": {"type": "str", "default": None},
    "failback_allowed": {"type": "str", "default": None},
    "failover": {"type": "bool", "default": None},
    "failure_reason": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "health": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "inode_count": {"type": "str", "default": None},
    "internal": {"type": "bool", "default": None},
    "is_gn_enabled": {"type": "bool", "default": None},
    "is_local": {"type": "bool", "default": None},
    "last_restore_point_creation_time": {"type": "str", "default": None},
    "last_restore_point_time": {"type": "str", "default": None},
    "last_snapshot_creation_time": {"type": "str", "default": None},
    "last_uploading_restore_point_logical_size": {"type": "str", "default": None},
    "last_uploading_restore_point_physical_size": {"type": "str", "default": None},
    "last_uploading_restore_point_progress": {"type": "int", "default": None},
    "last_uploading_restore_point_state": {"type": "str", "default": None},
    "lease_expiry_time": {"type": "int", "default": None},
    "logical_size": {"type": "int", "default": None},
    "name": {"type": "str", "default": None},
    "peer_cluster_name": {"type": "str", "default": None},
    "peer_connection_state": {"type": "str", "default": None},
    "physical_size": {"type": "int", "default": None},
    "progress": {"type": "str", "default": None},
    "protection_policy_id": {"type": "str", "default": None},
    "protection_policy_name": {"type": "str", "default": None},
    "remote_tenant_guid": {"type": "str", "default": None},
    "remote_tenant_name": {"type": "str", "default": None},
    "replication_policy": {"type": "str", "default": None},
    "replication_target_name": {"type": "str", "default": None},
    "restore_task": {"type": "str", "default": None},
    "role": {"type": "str", "default": None},
    "role_change_eta_sec": {"type": "int", "default": None},
    "role_change_progress_promil": {"type": "int", "default": None},
    "source_dir": {"type": "str", "default": None},
    "state": {
        "type": "str",
        "default": None,
        "choices": [
            "Failed",
            "DELETED_ON_PEER",
            "N/A",
            "INVALID",
            "DELETE_PENDING",
            "Active",
            "Suspended",
            "Syncing",
            "Finalizing",
            "Initializing",
            "Initial Scan",
            "Initial Sync",
            "Initial Sync Suspended",
            "Writable",
            "Blocked",
            "Sync Failed",
            "UNKNOWN",
            "Calculating...",
            "Local",
            "Error",
            "Degraded",
            "INITIAL_SYNC",
            "INCREMENTAL_SYNC",
            "INCREMENTAL_SYNC_SUSPENDED",
            "ERROR_DEPRECATED",
            "LOCAL_ACTIVE",
            "INITIAL_SCAN",
            "DELETE_READY",
            "INITIAL_SYNC_SUSPENDED",
            "LOCAL_SUSPENDED",
            "PENDING_SYNC",
            "PENDING_CLEANUP",
        ],
    },
    "state_description": {"type": "str", "default": None},
    "sync_disconnect_time": {"type": "int", "default": None},
    "sync_interval": {"type": "int", "default": None},
    "target_exported_dir": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "tenant_name": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ProtectedpathInfoResource(BaseInfoResource):
    """Read-only list manager for ProtectedPath."""

    resource_name = "protectedpaths"
    return_key = "protectedpaths"
    filter_fields = {
        "aggr_phys_estimation",
        "bucket_name",
        "bw",
        "capabilities",
        "enabled",
        "estimated_read_only_time",
        "eta",
        "failback_allowed",
        "failover",
        "failure_reason",
        "guid",
        "health",
        "id",
        "inode_count",
        "internal",
        "is_gn_enabled",
        "is_local",
        "last_restore_point_creation_time",
        "last_restore_point_time",
        "last_snapshot_creation_time",
        "last_uploading_restore_point_logical_size",
        "last_uploading_restore_point_physical_size",
        "last_uploading_restore_point_progress",
        "last_uploading_restore_point_state",
        "lease_expiry_time",
        "logical_size",
        "name",
        "peer_cluster_name",
        "peer_connection_state",
        "physical_size",
        "progress",
        "protection_policy_id",
        "protection_policy_name",
        "remote_tenant_guid",
        "remote_tenant_name",
        "replication_policy",
        "replication_target_name",
        "restore_task",
        "role",
        "role_change_eta_sec",
        "role_change_progress_promil",
        "source_dir",
        "state",
        "state_description",
        "sync_disconnect_time",
        "sync_interval",
        "target_exported_dir",
        "tenant_id",
        "tenant_name",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "policy_id": {"min": (5, 5), "max": None},
        "remote_tenant_name": {"min": (5, 5), "max": None},
        "view_replication_enabled": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ProtectedpathInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
