#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: quotagroups_info
short_description: List VAST QuotaGroup resources
description:
  - List VAST QuotaGroup resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  cluster:
    description: "Parent Cluster (optional filter)"
    type: str

  cluster_id:
    description: "Parent Cluster ID (optional filter)"
    type: int

  default_email:
    description: |
      The default email for sending user quota alert emails. This is used if no suffix is set and no address is found
      on providers. (optional filter)
    type: str

  enable_alarms:
    description: "Enable alarms when users or groups are exceeding their limit (optional filter)"
    type: bool

  enable_email_providers:
    description: |
      Enable this setting to query Active Directory and LDAP services for user emails when sending userquota alert
      emails. If enabled, the provider query is the first priority source for a user's email. If a user's email is not
      found on the provider, a global email suffix is used if configured in cluster settings. If no suffix is set,
      default_email is used. (optional filter)
    type: bool

  grace_period:
    description: "Quota enforcement grace period in seconds, minutes, hours or days. Example: 90m (optional filter)"
    type: str

  guid:
    description: "Quota guid (optional filter)"
    type: str

  hard_limit:
    description: "Filter by hard limit (optional filter)"
    type: str

  hard_limit_inodes:
    description: "Filter by hard limit inodes (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  internal:
    description: "Filter by internal (optional filter)"
    type: bool

  is_physical_quota:
    description: "Set to true to Limit by Physical Capacity. Cannot be updated. (optional filter)"
    type: bool

  is_user_quota:
    description: "Set to true to enable user and group quotas. False by default. (optional filter)"
    type: bool

  last_user_quotas_update:
    description: "Time of last user quota update (optional filter)"
    type: str

  name:
    description: "Filter by name (optional filter)"
    type: str

  num_blocked_users:
    description: |
      The number of users that are blocked from writing to the quota path due to exceeding a hard user/group quota
      limit. (optional filter)
    type: int

  num_exceeded_users:
    description: "The number of users that have exceeded a user quota (optional filter)"
    type: int

  percent_capacity:
    description: "Percentage in use of the capacity hard limit (optional filter)"
    type: int

  percent_inodes:
    description: "Percentage in use of the hard limit on directories and unique files (optional filter)"
    type: int

  pretty_grace_period:
    description: |
      Quota enforcement grace period expressed in human readable format as seconds, minutes, hours or days. Example: 12
      days 43 minutes 43 seconds (optional filter)
    type: str

  pretty_grace_period_expiration:
    description: |
      The time remaining until the end of the grace period, in human readable format. Displayed when soft limit is
      exceeded. (optional filter)
    type: str

  pretty_state:
    description: "Filter by pretty state (optional filter)"
    type: str

  quotas_count:
    description: "Filter by quotas count (optional filter)"
    type: int

  show_user_rules:
    description: "Filter by show user rules (optional filter)"
    type: bool

  soft_limit:
    description: "Filter by soft limit (optional filter)"
    type: str

  soft_limit_inodes:
    description: "Filter by soft limit inodes (optional filter)"
    type: str

  state:
    description: "Quota state (optional filter)"
    type: str
    choices:
      - SOFT_BOTH_EXCEEDED
      - INODE_SOFT_EXCEEDED
      - SOFT_EXCEEDED
      - HARD_BOTH_EXCEEDED
      - INODE_HARD_EXCEEDED
      - HARD_EXCEEDED
      - GRACE_EXPIRED
      - OK
      - FAILED

  sync_state:
    description: "Filter by sync state (optional filter)"
    type: str

  system_id:
    description: "Filter by system id (optional filter)"
    type: str

  tenant_id:
    description: "Filter by tenant. Specify tenant ID. (optional filter)"
    type: int

  tenant_name:
    description: "Tenant Name (optional filter)"
    type: str

  tenant_name__icontains:
    description: "Tenant name to filter by (optional filter)"
    type: str

  time_to_block:
    description: |
      The time remaining until the end of the grace period. Displayed when soft limit is exceeded. (optional filter)
    type: str

  title:
    description: "Quota name (optional filter)"
    type: str

  url:
    description: "Endpoint URL for API operations on the quota (optional filter)"
    type: str

  used_capacity:
    description: "Used capacity in bytes (optional filter)"
    type: int

  used_capacity_tb:
    description: "Used capacity in TB (optional filter)"
    type: float

  used_effective_capacity:
    description: "Used effective capacity in bytes (optional filter)"
    type: int

  used_effective_capacity_tb:
    description: "Used effective capacity in TB (optional filter)"
    type: float

  used_inodes:
    description: "Number of directories and unique files under the path (optional filter)"
    type: int

  used_limited_capacity:
    description: "Filter by used limited capacity (optional filter)"
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all quotagroups
  vastdata.vms.quotagroups_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: quotagroups_result

- name: List quotagroups filtered by name
  vastdata.vms.quotagroups_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_quotagroups
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
quotagroups:
  description: List of matching quotagroups resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "cluster": {"type": "str", "default": None},
    "cluster_id": {"type": "int", "default": None},
    "default_email": {"type": "str", "default": None},
    "enable_alarms": {"type": "bool", "default": None},
    "enable_email_providers": {"type": "bool", "default": None},
    "grace_period": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "hard_limit": {"type": "str", "default": None},
    "hard_limit_inodes": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "internal": {"type": "bool", "default": None},
    "is_physical_quota": {"type": "bool", "default": None},
    "is_user_quota": {"type": "bool", "default": None},
    "last_user_quotas_update": {"type": "str", "default": None},
    "name": {"type": "str", "default": None},
    "num_blocked_users": {"type": "int", "default": None},
    "num_exceeded_users": {"type": "int", "default": None},
    "percent_capacity": {"type": "int", "default": None},
    "percent_inodes": {"type": "int", "default": None},
    "pretty_grace_period": {"type": "str", "default": None},
    "pretty_grace_period_expiration": {"type": "str", "default": None},
    "pretty_state": {"type": "str", "default": None},
    "quotas_count": {"type": "int", "default": None},
    "show_user_rules": {"type": "bool", "default": None},
    "soft_limit": {"type": "str", "default": None},
    "soft_limit_inodes": {"type": "str", "default": None},
    "state": {
        "type": "str",
        "default": None,
        "choices": [
            "SOFT_BOTH_EXCEEDED",
            "INODE_SOFT_EXCEEDED",
            "SOFT_EXCEEDED",
            "HARD_BOTH_EXCEEDED",
            "INODE_HARD_EXCEEDED",
            "HARD_EXCEEDED",
            "GRACE_EXPIRED",
            "OK",
            "FAILED",
        ],
    },
    "sync_state": {"type": "str", "default": None},
    "system_id": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "tenant_name": {"type": "str", "default": None},
    "tenant_name__icontains": {"type": "str", "default": None},
    "time_to_block": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
    "used_capacity": {"type": "int", "default": None},
    "used_capacity_tb": {"type": "float", "default": None},
    "used_effective_capacity": {"type": "int", "default": None},
    "used_effective_capacity_tb": {"type": "float", "default": None},
    "used_inodes": {"type": "int", "default": None},
    "used_limited_capacity": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class QuotagroupInfoResource(BaseInfoResource):
    """Read-only list manager for QuotaGroup."""

    resource_name = "quotagroups"
    return_key = "quotagroups"
    filter_fields = {
        "cluster",
        "cluster_id",
        "default_email",
        "enable_alarms",
        "enable_email_providers",
        "grace_period",
        "guid",
        "hard_limit",
        "hard_limit_inodes",
        "id",
        "internal",
        "is_physical_quota",
        "is_user_quota",
        "last_user_quotas_update",
        "name",
        "num_blocked_users",
        "num_exceeded_users",
        "percent_capacity",
        "percent_inodes",
        "pretty_grace_period",
        "pretty_grace_period_expiration",
        "pretty_state",
        "quotas_count",
        "show_user_rules",
        "soft_limit",
        "soft_limit_inodes",
        "state",
        "sync_state",
        "system_id",
        "tenant_id",
        "tenant_name",
        "tenant_name__icontains",
        "time_to_block",
        "title",
        "url",
        "used_capacity",
        "used_capacity_tb",
        "used_effective_capacity",
        "used_effective_capacity_tb",
        "used_inodes",
        "used_limited_capacity",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # resource introduced in this VMS version
    field_versions = {
        "default_email": {"min": (5, 5), "max": None},
        "default_group_quota": {"min": (5, 5), "max": None},
        "default_user_quota": {"min": (5, 5), "max": None},
        "enable_alarms": {"min": (5, 5), "max": None},
        "enable_email_providers": {"min": (5, 5), "max": None},
        "grace_period": {"min": (5, 5), "max": None},
        "group_quotas": {"min": (5, 5), "max": None},
        "hard_limit": {"min": (5, 5), "max": None},
        "hard_limit_inodes": {"min": (5, 5), "max": None},
        "is_user_quota": {"min": (5, 5), "max": None},
        "name": {"min": (5, 5), "max": None},
        "soft_limit": {"min": (5, 5), "max": None},
        "soft_limit_inodes": {"min": (5, 5), "max": None},
        "tenant_id": {"min": (5, 5), "max": None},
        "user_quotas": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = QuotagroupInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
