#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: s3lifecyclerules_info
short_description: List VAST S3LifeCycleRule resources
description:
  - List VAST S3LifeCycleRule resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  abort_mpu_days_after_initiation:
    description: "The number of days until expiration after an incomplete multipart upload (optional filter)"
    type: int

  enabled:
    description: "Filter by enabled (optional filter)"
    type: bool

  expiration_date:
    description: "The expiration date of the object (optional filter)"
    type: str

  expiration_days:
    description: "The number of days from creation until an object expires (optional filter)"
    type: int

  expired_obj_delete_marker:
    description: "If true, delete markets of objects are removed when objects expire (optional filter)"
    type: bool

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  id:
    description: "The ID of an S3 Lifecycle rule (optional filter)"
    type: int

  max_size:
    description: "Maximum object size (optional filter)"
    type: int

  min_size:
    description: "Minimum object size (optional filter)"
    type: int

  name:
    description: "A unique name (optional filter)"
    type: str

  newer_noncurrent_versions:
    description: "The number of newer versions to retain (optional filter)"
    type: int

  noncurrent_days:
    description: "Number of days at which objects become noncurrent (optional filter)"
    type: int

  object_age_attr:
    description: "Defines which time to use for expiration. (optional filter)"
    type: str
    choices: ["M_TIME", "A_TIME", "C_TIME"]

  prefix:
    description: |
      Defines a scope of elements (objects, files or directories) by prefix. All objects with keys that begin with the
      specified prefix are included in the scope. In file and directory nomenclature, a prefix is a file and/or
      directory path within the view that can include part of the file or directory name. For example, 'sales/jan'
      would include the file sales/january and the directory sales/jan/week1/. No characters are handled as wildcards.
      (optional filter)
    type: str

  title:
    description: "Filter by title (optional filter)"
    type: str

  url:
    description: "Filter by url (optional filter)"
    type: str

  view_id:
    description: "The ID of a view, when the rule applies to all objects in a view (bucket) (optional filter)"
    type: int

  view_path:
    description: "The path of a view, when the rule applies to all objects in a view (bucket) (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all s3lifecyclerules
  vastdata.vms.s3lifecyclerules_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: s3lifecyclerules_result

- name: List s3lifecyclerules filtered by name
  vastdata.vms.s3lifecyclerules_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_s3lifecyclerules
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
s3lifecyclerules:
  description: List of matching s3lifecyclerules resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "abort_mpu_days_after_initiation": {"type": "int", "default": None},
    "enabled": {"type": "bool", "default": None},
    "expiration_date": {"type": "str", "default": None},
    "expiration_days": {"type": "int", "default": None},
    "expired_obj_delete_marker": {"type": "bool", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "max_size": {"type": "int", "default": None},
    "min_size": {"type": "int", "default": None},
    "name": {"type": "str", "default": None},
    "newer_noncurrent_versions": {"type": "int", "default": None},
    "noncurrent_days": {"type": "int", "default": None},
    "object_age_attr": {"type": "str", "default": None, "choices": ["M_TIME", "A_TIME", "C_TIME"]},
    "prefix": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
    "view_id": {"type": "int", "default": None},
    "view_path": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class S3lifecycleruleInfoResource(BaseInfoResource):
    """Read-only list manager for S3LifeCycleRule."""

    resource_name = "s3lifecyclerules"
    return_key = "s3lifecyclerules"
    filter_fields = {
        "abort_mpu_days_after_initiation",
        "enabled",
        "expiration_date",
        "expiration_days",
        "expired_obj_delete_marker",
        "guid",
        "id",
        "max_size",
        "min_size",
        "name",
        "newer_noncurrent_versions",
        "noncurrent_days",
        "object_age_attr",
        "prefix",
        "title",
        "url",
        "view_id",
        "view_path",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "tags": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = S3lifecycleruleInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
