#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: s3policies_info
short_description: List VAST S3Policy resources
description:
  - List VAST S3Policy resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  enabled:
    description: "Filter by enabled (optional filter)"
    type: bool

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  iam_roles__id:
    description: "Filter by iam roles  id (optional filter)"
    type: str

  id:
    description: "The ID of an S3 identity policy. (optional filter)"
    type: int

  is_replicated:
    description: "Filter by is replicated (optional filter)"
    type: bool

  name:
    description: "The name of the S3 identity policy. (optional filter)"
    type: str

  policy:
    description: "The S3 identity policy in JSON format. (optional filter)"
    type: str

  tenant_id:
    description: "Filter by tenant id (optional filter)"
    type: int

  tenant_name:
    description: "Filter by tenant name (optional filter)"
    type: str

  title:
    description: "Filter by title (optional filter)"
    type: str

  url:
    description: "Filter by url (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all s3policies
  vastdata.vms.s3policies_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: s3policies_result

- name: List s3policies filtered by name
  vastdata.vms.s3policies_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_s3policies
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
s3policies:
  description: List of matching s3policies resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "enabled": {"type": "bool", "default": None},
    "guid": {"type": "str", "default": None},
    "iam_roles__id": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "is_replicated": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "policy": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "tenant_name": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class S3policyInfoResource(BaseInfoResource):
    """Read-only list manager for S3Policy."""

    resource_name = "s3policies"
    return_key = "s3policies"
    filter_fields = {
        "enabled",
        "guid",
        "iam_roles__id",
        "id",
        "is_replicated",
        "name",
        "policy",
        "tenant_id",
        "tenant_name",
        "title",
        "url",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = S3policyInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
