#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: supportbundlesqueue_info
short_description: List VAST SupportBundle resources
description:
  - List VAST SupportBundle resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  aggregated:
    description: "Aggregate harvests into final bundle (deprecated) (optional filter)"
    type: bool

  astron_args:
    description: "Filter by astron args (optional filter)"
    type: str

  bundle_file:
    description: "Filter by bundle file (optional filter)"
    type: str

  bundle_size:
    description: "Filter by bundle size (optional filter)"
    type: str

  bundle_url:
    description: "URL to access/download support bundle file (optional filter)"
    type: str

  callhome:
    description: "Filter by callhome (optional filter)"
    type: bool

  cluster:
    description: "Parent Cluster (optional filter)"
    type: str

  cluster_id:
    description: "Filter by cluster id (optional filter)"
    type: int

  cnode_ids:
    description: |
      Array of IDs of specific CNodes from which logs are collected. If not specified, logs are collected from all
      CNodes. (optional filter)
    type: str

  cnodes_only:
    description: "Filter by cnodes only (optional filter)"
    type: bool

  core:
    description: "Filter by core (optional filter)"
    type: str

  create_datetime:
    description: "Filter by create datetime (optional filter)"
    type: str

  created:
    description: "Bundle creation time (optional filter)"
    type: str

  delete_after_send:
    description: "Delete the bundle immediately after successfully uploading (optional filter)"
    type: bool

  dnode_ids:
    description: |
      Array of IDs of specific DNodes from which logs are collected. If not specified, logs are collected from all
      DNodes. (optional filter)
    type: str

  dnodes_only:
    description: "Filter by dnodes only (optional filter)"
    type: bool

  end_time:
    description: "End time of logs in UTC+3 (optional filter)"
    type: str

  guid:
    description: "Filter by guid (optional filter)"
    type: str

  hubble_args:
    description: "Filter by hubble args (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  level:
    description: "Bundle level e.g. small, medium, large (optional filter)"
    type: str

  luna_args:
    description: "Filter by luna args (optional filter)"
    type: str

  management:
    description: "Filter by management (optional filter)"
    type: bool

  max_size:
    description: "Trace files bundle size limit in GB for each node (optional filter)"
    type: float

  mem_traces:
    description: "Filter by mem traces (optional filter)"
    type: bool

  metrics:
    description: "Filter by metrics (optional filter)"
    type: bool

  name:
    description: "Filter by name (optional filter)"
    type: str

  obfuscated:
    description: |
      True if the bundle is obfuscated. If obfuscated, all bundled objects are converted to text and obfuscated. Any
      data that cannot be converted to text is not included in the bundle. The following types of information are
      replaced with a non-reversible hash: file and directory names, IP addresses, host names, user names, passwords,
      MAC addresses. (optional filter)
    type: bool

  performance:
    description: "Filter by performance (optional filter)"
    type: bool

  platform:
    description: "Filter by platform (optional filter)"
    type: bool

  position_in_queue:
    description: "Position of the support bundle in the queue (optional filter)"
    type: int

  prefix:
    description: "Identifying label included in the bundle file name as a prefix (optional filter)"
    type: str

  preset:
    description: "Type of predefined preset bundle (optional filter)"
    type: str

  send_now:
    description: "Upload support bundle after creation (optional filter)"
    type: bool

  start_time:
    description: "Start time of logs in UTC+3 (optional filter)"
    type: str

  state:
    description: "State of the bundle (optional filter)"
    type: str
    choices:
      - UNKNOWN
      - CREATING
      - CREATED
      - FAILED
      - DELETING
      - DELETED
      - MODIFYING
      - MODIFIED
      - PARTIALLY_CREATED
      - COMPLETING

  text:
    description: "Include only textual logs in bundle (optional filter)"
    type: bool

  traces:
    description: "Filter by traces (optional filter)"
    type: bool

  url:
    description: "Filter by url (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all supportbundlesqueue
  vastdata.vms.supportbundlesqueue_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: supportbundlesqueue_result

- name: List supportbundlesqueue filtered by name
  vastdata.vms.supportbundlesqueue_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_supportbundlesqueue
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
supportbundlesqueue:
  description: List of matching supportbundlesqueue resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "aggregated": {"type": "bool", "default": None},
    "astron_args": {"type": "str", "default": None},
    "bundle_file": {"type": "str", "default": None},
    "bundle_size": {"type": "str", "default": None},
    "bundle_url": {"type": "str", "default": None},
    "callhome": {"type": "bool", "default": None},
    "cluster": {"type": "str", "default": None},
    "cluster_id": {"type": "int", "default": None},
    "cnode_ids": {"type": "str", "default": None},
    "cnodes_only": {"type": "bool", "default": None},
    "core": {"type": "str", "default": None},
    "create_datetime": {"type": "str", "default": None},
    "created": {"type": "str", "default": None},
    "delete_after_send": {"type": "bool", "default": None},
    "dnode_ids": {"type": "str", "default": None},
    "dnodes_only": {"type": "bool", "default": None},
    "end_time": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "hubble_args": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "level": {"type": "str", "default": None},
    "luna_args": {"type": "str", "default": None},
    "management": {"type": "bool", "default": None},
    "max_size": {"type": "float", "default": None},
    "mem_traces": {"type": "bool", "default": None},
    "metrics": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "obfuscated": {"type": "bool", "default": None},
    "performance": {"type": "bool", "default": None},
    "platform": {"type": "bool", "default": None},
    "position_in_queue": {"type": "int", "default": None},
    "prefix": {"type": "str", "default": None},
    "preset": {"type": "str", "default": None},
    "send_now": {"type": "bool", "default": None},
    "start_time": {"type": "str", "default": None},
    "state": {
        "type": "str",
        "default": None,
        "choices": [
            "UNKNOWN",
            "CREATING",
            "CREATED",
            "FAILED",
            "DELETING",
            "DELETED",
            "MODIFYING",
            "MODIFIED",
            "PARTIALLY_CREATED",
            "COMPLETING",
        ],
    },
    "text": {"type": "bool", "default": None},
    "traces": {"type": "bool", "default": None},
    "url": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class SupportbundlesqueueInfoResource(BaseInfoResource):
    """Read-only list manager for SupportBundle."""

    resource_name = "supportbundlesqueue"
    return_key = "supportbundlesqueue"
    filter_fields = {
        "aggregated",
        "astron_args",
        "bundle_file",
        "bundle_size",
        "bundle_url",
        "callhome",
        "cluster",
        "cluster_id",
        "cnode_ids",
        "cnodes_only",
        "core",
        "create_datetime",
        "created",
        "delete_after_send",
        "dnode_ids",
        "dnodes_only",
        "end_time",
        "guid",
        "hubble_args",
        "id",
        "level",
        "luna_args",
        "management",
        "max_size",
        "mem_traces",
        "metrics",
        "name",
        "obfuscated",
        "performance",
        "platform",
        "position_in_queue",
        "prefix",
        "preset",
        "send_now",
        "start_time",
        "state",
        "text",
        "traces",
        "url",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # resource introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = SupportbundlesqueueInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
