#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: tenants/metric_labels

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tenant_metric_labels
short_description: Manage tenant metric labels
description:
  - Manage tenant metric labels.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  default_value:
    description: "The default value for this metric label."
    type: str

  description:
    description: "Description of the metric label purpose."
    type: str

  key:
    description: "The unique key for the metric label."
    type: str
    required: true
  state:
    description: Desired state.
    type: str
    choices: [present, absent]
    default: present
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Manage tenant metric labels
  vastdata.vms.tenant_metric_labels:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
tenant_metric_labels:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "default_value": {"type": "str", "default": None},
    "description": {"type": "str", "default": None},
    "key": {"type": "str", "required": True, "no_log": False},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class TenantMetricLabels(SubEndpointResource):
    parent_resource = "tenants"
    sub_path = "metric_labels"
    path_has_id = False
    supported_operations = frozenset({CrudCapability.CREATE, CrudCapability.DELETE, CrudCapability.READ})
    collection_identity = ["key"]
    identity_field_map = {}
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # sub-endpoint introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS


def _apply_tenant_metric_labels_customizations():  # isort: skip
    """Keyed collection idempotent CRUD for tenant metric labels."""
    from ansible_collections.vastdata.vms.plugins.module_utils.vast.keyed_collection import (
        _keyed_collection_find_existing,
        _keyed_collection_identity_matches,
        _keyed_collection_list_rows,
        _keyed_collection_run,
    )

    TenantMetricLabels._list_rows = _keyed_collection_list_rows
    TenantMetricLabels._identity_matches = _keyed_collection_identity_matches
    TenantMetricLabels._find_existing = _keyed_collection_find_existing
    TenantMetricLabels.run = _keyed_collection_run


_apply_tenant_metric_labels_customizations()


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TenantMetricLabels(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
