#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tenants
short_description: Manage VAST Tenant resources
description:
  - Create, update, or delete VAST Tenant resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  access_ip_ranges:
    description: |
      Restricts tenant login access to specified source IP ranges. Enter as single IPs (1.1.1.1), ranges (1.2.3.4 -
      1.2.3.6), or CIDR (1.1.1.0/24).
    type: list
    elements: str

  ad_provider_id:
    description: "Active Directory provider ID"
    type: int

  allow_disabled_users:
    description: "Allow IO from users whose Active Directory accounts are explicitly disabled."
    type: bool

  allow_locked_users:
    description: |
      Allow IO from users whose Active Directory accounts are locked out by lockout policies due to unsuccessful login
      attempts.
    type: bool

  allowed_delegations:
    description: "Defines the possible types of NFSv4 delegations"
    type: str
    choices: ["NONE", "READ", "WRITE", "READ_WRITE"]

  application_users_group_name:
    description: "The name of the group that will be used for application users"
    type: str

  capacity_rules:
    description: "Capacity Rules"
    type: dict

  client_ip_ranges:
    description: |
      Array of ranges of client IPs to be served by the tenant. For client requests made to a VIP that belongs to a VIP
      Pool that is not associated to a specific tenant, the client's source IP is checked against the Client IPs that
      are defined within each tenant. That check determines access. The client IPs that you associate with each tenant
      must be unique per tenant.
    type: list
    elements: list

  data_engine_role_enabled:
    description: "Whether to create dedicated Role for application users group"
    type: bool

  data_engine_s3_policy_enabled:
    description: "Whether to create dedicated Identity Policy for application users group"
    type: bool

  default_others_share_level_perm:
    description: "Default Share-level permissions for Others"
    type: str
    choices: ["READ", "CHANGE", "FULL"]

  domain_name:
    description: "Domain name to incorporate into the VMS tenant login page URL."
    type: str

  encryption_crn:
    description: "Tenant's encryption group unique identifier (deprecated)"
    type: str

  encryption_group:
    description: "Tenant's encryption group unique identifier"
    type: str

  grant_unrequested_delegations_by_default:
    description: |
      When enabled, the server may grant delegations based on share access even if not explicitly requested by the
      client
    type: bool

  identity_provider_name:
    description: |
      Sets a configured SAML login provider to enable for the tenant. When set, users defined on the specified SAML
      provider can login to the tenant VMS as tenant admin users.
    type: str

  is_nfsv42_supported:
    description: "Enable NFSv4.2"
    type: bool

  krb_provider_id:
    description: "Kerberos provider ID"
    type: int

  ldap_provider_id:
    description: "Open-LDAP provider ID specified separately by the user"
    type: int

  local_provider_id:
    description: "Local provider ID"
    type: int

  login_name_primary_provider:
    description: "Login name primary provider type"
    type: str
    choices: ["NONE", "LDAP", "NIS", "AD", "LOCAL"]

  max_views:
    description: "Max views we can create on this tenant (0:unlimted as default)"
    type: int

  name:
    description: "A name for the tenant"
    type: str
    required: true

  nis_provider_id:
    description: "NIS provider ID"
    type: int

  oidc_provider_id:
    description: "OIDC provider ID"
    type: int

  posix_primary_provider:
    description: "POSIX primary provider type"
    type: str
    choices: ["NONE", "LDAP", "NIS", "AD"]

  preferred_owning_group:
    description: "Set to prefer GID of the user as the owning group of the file"
    type: str
    choices: ["PROTOCOL_BASED", "POSIX_GID"]

  qos:
    description: "Qos"
    type: dict

  require_smb_signing:
    description: "Require SMB signing"
    type: bool

  smb_administrators_group_name:
    description: |
      Optional custom name to specify a non default privileged group. If not set, privileged group is the Backup
      Operators domain group.
    type: str

  smb_encryption_state:
    description: "Defines the encryption level for SMB"
    type: str
    choices: ["OFF", "AVAILABLE", "DESIRED", "REQUIRED"]

  smb_privileged_group_full_access:
    description: |
      True=The SMB privileged user group has read and write control access. Members of the group can perform backup and
      restore operations on all files and directories, without requiring read or write access to the specific files and
      directories. False=the privileged group has read only access.
    type: bool

  smb_privileged_group_sid:
    description: |
      Optional custom SID to specify a non default SMB privileged group. If not set, SMB privileged group is the Backup
      Operators domain group.
    type: str

  smb_privileged_user_name:
    description: |
      Optional custom username for the SMB privileged user. If not set, the SMB privileged user name is 'vastadmin'
    type: str

  tenant_admins_group_name:
    description: |
      Specifies a group on an AD or LDAP provider. Enables users in the group to log into the tenant VMS as Tenant
      Admin users. In order to be granted permissions to do any configuration, the same users need to belong to groups
      on the provider that are associated with VMS manager user roles for tenant admin type users on the tenant.
    type: str

  trash_gid:
    description: "GID with permissions to the trash folder"
    type: int

  use_smb_native:
    description: "Use native SMB authentication"
    type: bool

  use_smb_privileged_group:
    description: "Enables SMB privileged user group"
    type: bool

  use_smb_privileged_user:
    description: "Enables SMB privileged user"
    type: bool
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create Tenant
  vastdata.vms.tenants:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-name"
    state: present

- name: Update Tenant
  vastdata.vms.tenants:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete Tenant
  vastdata.vms.tenants:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
tenants:
  description: The tenants resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "access_ip_ranges": {"type": "list", "default": None, "elements": "str"},
    "ad_provider_id": {"type": "int", "default": None},
    "allow_disabled_users": {"type": "bool", "default": None},
    "allow_locked_users": {"type": "bool", "default": None},
    "allowed_delegations": {
        "type": "str",
        "default": None,
        "choices": [
            "NONE",
            "READ",
            "WRITE",
            "READ_WRITE",
        ],
    },
    "application_users_group_name": {"type": "str", "default": None},
    "capacity_rules": {"type": "dict", "default": None},
    "client_ip_ranges": {"type": "list", "default": None, "elements": "list"},
    "data_engine_role_enabled": {"type": "bool", "default": None},
    "data_engine_s3_policy_enabled": {"type": "bool", "default": None},
    "default_others_share_level_perm": {
        "type": "str",
        "default": None,
        "choices": [
            "READ",
            "CHANGE",
            "FULL",
        ],
    },
    "domain_name": {"type": "str", "default": None},
    "encryption_crn": {"type": "str", "default": None},
    "encryption_group": {"type": "str", "default": None},
    "grant_unrequested_delegations_by_default": {"type": "bool", "default": None},
    "identity_provider_name": {"type": "str", "default": None},
    "is_nfsv42_supported": {"type": "bool", "default": None},
    "krb_provider_id": {"type": "int", "default": None},
    "ldap_provider_id": {"type": "int", "default": None},
    "local_provider_id": {"type": "int", "default": None},
    "login_name_primary_provider": {
        "type": "str",
        "default": None,
        "choices": [
            "NONE",
            "LDAP",
            "NIS",
            "AD",
            "LOCAL",
        ],
    },
    "max_views": {"type": "int", "default": None},
    "name": {"type": "str", "required": True},
    "nis_provider_id": {"type": "int", "default": None},
    "oidc_provider_id": {"type": "int", "default": None},
    "posix_primary_provider": {"type": "str", "default": None, "choices": ["NONE", "LDAP", "NIS", "AD"]},
    "preferred_owning_group": {"type": "str", "default": None, "choices": ["PROTOCOL_BASED", "POSIX_GID"]},
    "qos": {"type": "dict", "default": None},
    "require_smb_signing": {"type": "bool", "default": None},
    "smb_administrators_group_name": {"type": "str", "default": None},
    "smb_encryption_state": {
        "type": "str",
        "default": None,
        "choices": [
            "OFF",
            "AVAILABLE",
            "DESIRED",
            "REQUIRED",
        ],
    },
    "smb_privileged_group_full_access": {"type": "bool", "default": None},
    "smb_privileged_group_sid": {"type": "str", "default": None},
    "smb_privileged_user_name": {"type": "str", "default": None},
    "tenant_admins_group_name": {"type": "str", "default": None},
    "trash_gid": {"type": "int", "default": None},
    "use_smb_native": {"type": "bool", "default": None},
    "use_smb_privileged_group": {"type": "bool", "default": None},
    "use_smb_privileged_user": {"type": "bool", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class TenantResource(BaseResource):
    """Resource manager for Tenant."""

    resource_name = "tenants"
    singular = "tenant"
    lookup_field = "name"
    async_delete = True


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TenantResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
