#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tenant_metric_label_values_info
short_description: Manage tenant metric label values
description:
  - Manage tenant metric label values.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  tenant_id:
    description: ID of the tenant.
    type: int
    required: true
  created_at:
    description: "Timestamp when the metric label value was created. (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  value:
    description: "The value for this metric label for the tenant. (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List tenant_metric_label_values
  vastdata.vms.tenant_metric_label_values_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    tenant_id: 1
  register: tenant_metric_label_values_result
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
tenant_metric_label_values:
  description: List of matching sub-resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import SubEndpointInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "tenant_id": {"required": True, "type": "int"},
    "created_at": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "value": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class TenantMetricLabelValuesInfo(SubEndpointInfoResource):
    parent_resource = "tenants"
    sub_path = "metric_label_values"
    path_has_id = True
    return_key = "tenant_metric_label_values"
    filter_fields = {"created_at", "id", "value"}
    parent_id_param = "tenant_id"
    generated_min_version = (5, 4)
    resource_min_version = (5, 5)


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TenantMetricLabelValuesInfo(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
