#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0
#
# Sub-endpoint module: tenants/metric_label_values/bulk

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tenant_metric_label_values_bulk
short_description: Bulk read or replace all tenant metric label values
description:
  - Bulk read or replace all tenant metric label values.
  - Supports check_mode and diff.
version_added: "1.0.0"
options:
  tenant_id:
    description: "ID of the tenant"
    type: int
    required: true
  values:
    description: |
      Complete map of metric label key to value to apply. Omit to read the current map without changing it. When
      supplied, replaces the entire map: label keys not present revert to their default_value. Keys must match existing
      metric labels or the API rejects the request. Keys and values are coerced to strings.
    type: dict
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Bulk read or replace all tenant metric label values
  vastdata.vms.tenant_metric_label_values_bulk:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    tenant_id: 1
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
tenant_metric_label_values_bulk:
  description: The sub-resource data.
  type: dict
  returned: always
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.sub_endpoint_resource import (
    CrudCapability,
    SubEndpointResource,
)

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "tenant_id": {"required": True, "type": "int"},
    "values": {"type": "dict", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC


# BEGIN AUTOGENERATED RESOURCE_CLASS
class TenantMetricLabelValuesBulk(SubEndpointResource):
    parent_resource = "tenants"
    sub_path = "metric_label_values/bulk"
    path_has_id = True
    supported_operations = frozenset({CrudCapability.CREATE, CrudCapability.READ})
    parent_id_param = "tenant_id"
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # sub-endpoint introduced in this VMS version


# END AUTOGENERATED RESOURCE_CLASS


def _apply_tenant_metric_label_values_bulk_customizations():  # isort: skip
    """Whole-map idempotent read/replace for tenant metric label values.

    Generic SubEndpointResource treats READ+CREATE as a fire-and-forget action
    (always ``changed``). GET returns a ``{label_key: value}`` dict and POST
    replaces that map wholesale, so this run path compares the whole map first.
    Omit ``values`` to read; supply it to replace. The POST body is the map
    itself, not wrapped under a ``values`` key.

    ``_APIPath.get()`` always returns a list (dict body becomes ``[dict]``).
    Take index 0 here; ``_normalize_values`` stays dict-only.
    """
    from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastAPIError

    def _normalize_values(mapping):
        """Normalize to ``{str: str}``; the API stores label values as strings."""
        if mapping is None:
            return None
        return {str(key): str(value) for key, value in mapping.items()}

    def _run(self):
        result_key = self.module_result_key
        # Bypass SubEndpointResource.get() (it routes through ``.first()``, which
        # loses the whole-map shape). Match the sibling ``_run`` pattern in
        # apitoken_revoke / user_key: wrap the raw client call so VastAPIError
        # surfaces via fail_json (SystemExit terminates -- no explicit return).
        try:
            got = self._api_base.get() or []
        except VastAPIError as e:
            self.module.fail_json(msg=f"Failed to read {self.sub_path}: {e}")

        current = _normalize_values(got[0] if got else None) or {}
        desired = _normalize_values(self.params.get("values"))

        if desired is None or current == desired:
            self.module.exit_json(changed=False, **{result_key: current})

        if self.check_mode:
            self.module.exit_json(
                changed=True,
                diff={"before": current, "after": desired},
                **{result_key: desired},
            )

        updated = None
        try:
            updated = self.create(desired)
        except VastAPIError as e:
            self.module.fail_json(msg=str(e))

        after = _normalize_values(updated) or desired
        self.module.exit_json(
            changed=True,
            diff={"before": current, "after": after},
            **{result_key: after},
        )

    TenantMetricLabelValuesBulk.run = _run


_apply_tenant_metric_label_values_bulk_customizations()


# BEGIN AUTOGENERATED MAIN
def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TenantMetricLabelValuesBulk(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
