#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tlscertificates
short_description: Create, update, or delete VAST TLSCertificate resources
description:
  - Create, update, or delete VAST TLSCertificate resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  ca_certificate_file:
    description: "The new CA certificate file to upload. Requires VMS 5.5 or later."
    type: path

  ca_certificate_name:
    description: "Certificate name (default - the file name). Requires VMS 5.5 or later."
    type: str

  protocols:
    description: "Protocols Requires VMS 5.5 or later."
    type: list
    elements: str

  revocation_file:
    description: "The new certificate revocation list file to upload. Requires VMS 5.5 or later."
    type: path

  revocations_name:
    description: "Revocation name (default - the file name). Requires VMS 5.5 or later."
    type: str

  tenant_associate_param:
    description: "Tenant Associate Param Requires VMS 5.5 or later."
    type: str

  tenant_id:
    description: "Tenant ID Requires VMS 5.5 or later."
    type: int
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create TLSCertificate
  vastdata.vms.tlscertificates:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    ca_certificate_file: "/path/to/file"
    state: present

- name: Update TLSCertificate
  vastdata.vms.tlscertificates:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    ca_certificate_name: "example-value"
    state: present

- name: Delete TLSCertificate
  vastdata.vms.tlscertificates:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    ca_certificate_name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
tlscertificates:
  description: The tlscertificates resource data.
  type: dict
  returned: always
  sample:
    id: 1
    ca_certificate_name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "ca_certificate_file": {"type": "path", "default": None},
    "ca_certificate_name": {"type": "str", "default": None},
    "protocols": {"type": "list", "default": None, "elements": "str"},
    "revocation_file": {"type": "path", "default": None},
    "revocations_name": {"type": "str", "default": None},
    "tenant_associate_param": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class TlscertificateResource(BaseResource):
    """Resource manager for TLSCertificate."""

    resource_name = "tlscertificates"
    singular = "tlscertificate"
    lookup_field = "ca_certificate_name"
    create_only_fields = {"tenant_id"}  # Fields only valid during creation
    file_params = {"ca_certificate_file", "revocation_file"}  # Multipart file-upload params (local paths)
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # resource introduced in this VMS version
    field_versions = {
        "ca_certificate_file": {"min": (5, 5), "max": None},
        "ca_certificate_name": {"min": (5, 5), "max": None},
        "protocols": {"min": (5, 5), "max": None},
        "revocation_file": {"min": (5, 5), "max": None},
        "revocations_name": {"min": (5, 5), "max": None},
        "tenant_associate_param": {"min": (5, 5), "max": None},
        "tenant_id": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TlscertificateResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
