#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: tlscertificates_info
short_description: List VAST TLSCertificate resources
description:
  - List VAST TLSCertificate resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  ca_certificate_name:
    description: "Filter by ca certificate name (optional filter)"
    type: str

  ca_certificate_uploaded:
    description: "Filter by ca certificate uploaded (optional filter)"
    type: str

  created:
    description: "Filter by created (optional filter)"
    type: str

  expires_on:
    description: "Filter by expires on (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  protocols__icontains:
    description: "Protocol to see (optional filter)"
    type: str
    choices: ["NFS", "KAFKA"]

  revocations_exist:
    description: "Filter by revocations exist (optional filter)"
    type: bool

  revocations_expire_on:
    description: "Filter by revocations expire on (optional filter)"
    type: str

  revocations_name:
    description: "Filter by revocations name (optional filter)"
    type: str

  revocations_uploaded:
    description: "Filter by revocations uploaded (optional filter)"
    type: str

  tenant__id:
    description: "The tenant to show (optional filter)"
    type: int

  tenant__isnull:
    description: "Filter by global certificate (optional filter)"
    type: bool

  tenant_associate_param:
    description: "Filter by tenant associate param (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all tlscertificates
  vastdata.vms.tlscertificates_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: tlscertificates_result

- name: List tlscertificates filtered by ca_certificate_name
  vastdata.vms.tlscertificates_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    ca_certificate_name: example-value
  register: filtered_tlscertificates
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
tlscertificates:
  description: List of matching tlscertificates resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "ca_certificate_name": {"type": "str", "default": None},
    "ca_certificate_uploaded": {"type": "str", "default": None},
    "created": {"type": "str", "default": None},
    "expires_on": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "protocols__icontains": {"type": "str", "default": None, "choices": ["NFS", "KAFKA"]},
    "revocations_exist": {"type": "bool", "default": None},
    "revocations_expire_on": {"type": "str", "default": None},
    "revocations_name": {"type": "str", "default": None},
    "revocations_uploaded": {"type": "str", "default": None},
    "tenant__id": {"type": "int", "default": None},
    "tenant__isnull": {"type": "bool", "default": None},
    "tenant_associate_param": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class TlscertificateInfoResource(BaseInfoResource):
    """Read-only list manager for TLSCertificate."""

    resource_name = "tlscertificates"
    return_key = "tlscertificates"
    filter_fields = {
        "ca_certificate_name",
        "ca_certificate_uploaded",
        "created",
        "expires_on",
        "id",
        "protocols__icontains",
        "revocations_exist",
        "revocations_expire_on",
        "revocations_name",
        "revocations_uploaded",
        "tenant__id",
        "tenant__isnull",
        "tenant_associate_param",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    resource_min_version = (5, 5)  # resource introduced in this VMS version
    field_versions = {
        "ca_certificate_file": {"min": (5, 5), "max": None},
        "ca_certificate_name": {"min": (5, 5), "max": None},
        "protocols": {"min": (5, 5), "max": None},
        "revocation_file": {"min": (5, 5), "max": None},
        "revocations_name": {"min": (5, 5), "max": None},
        "tenant_associate_param": {"min": (5, 5), "max": None},
        "tenant_id": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = TlscertificateInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
