#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: users
short_description: Manage VAST User resources
description:
  - Create, update, or delete VAST User resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  allow_create_bucket:
    description: |
      Set to true to give the user permission to create S3 buckets. In case of conflict with an S3 identity policy
      attached to the user or to a relevant group, this setting is overridden.
    type: bool

  allow_delete_bucket:
    description: |
      Set to true to give the user permission to delete S3 buckets. In case of conflict with an S3 identity policy
      attached to the user or to a relevant group, this setting is overridden.
    type: bool

  gids:
    description: "List of group GIDs of all groups to which the user should belong."
    type: list
    elements: int

  leading_gid:
    description: "Leading GID"
    type: int

  local:
    description: "Not in use."
    type: bool

  local_provider_id:
    description: "The ID of the local provider to which to add the user"
    type: int

  name:
    description: "User name"
    type: str
    required: true

  password:
    description: "Password (Note: This credential is not returned by the API and only used during operations)"
    type: str

  s3_policies_ids:
    description: "Specify S3 policies to attach to the user."
    type: dict

  s3_superuser:
    description: |
      Set to true to give the user S3 superuser permission. In case of conflict with an S3 identity policy attached to
      the user or to a relevant group, this setting is overridden.
    type: bool

  uid:
    description: "NFS UID"
    type: int
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create User
  vastdata.vms.users:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-name"
    local_provider_id: 1
    state: present

- name: Update User
  vastdata.vms.users:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete User
  vastdata.vms.users:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
users:
  description: The users resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "allow_create_bucket": {"type": "bool", "default": None},
    "allow_delete_bucket": {"type": "bool", "default": None},
    "gids": {"type": "list", "default": None, "elements": "int"},
    "leading_gid": {"type": "int", "default": None},
    "local": {"type": "bool", "default": None},
    "local_provider_id": {"type": "int", "default": None},
    "name": {"type": "str", "required": True},
    "password": {"type": "str", "default": None, "no_log": True},
    "s3_policies_ids": {"type": "dict", "default": None},
    "s3_superuser": {"type": "bool", "default": None},
    "uid": {"type": "int", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class UserResource(BaseResource):
    """Resource manager for User."""

    resource_name = "users"
    singular = "user"
    lookup_field = "name"


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = UserResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
