#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: userquotas
short_description: Create, update, or delete VAST UserQuota resources
description:
  - Create, update, or delete VAST UserQuota resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  grace_period:
    description: |
      Quota enforcement grace period. An alarm is triggered and write operations are blocked if storage usage continues
      to exceed the soft limit for the grace period. Format: [DD] [HH:[MM:]]s
    type: str

  hard_limit:
    description: "Storage usage limit beyond which no writes will be allowed."
    type: int

  hard_limit_inodes:
    description: |
      Number of directories and unique files under the path beyond which no writes will be allowed. A file with
      multiple hardlinks is counted only once.
    type: int

  identifier:
    description: "Identifier"
    type: str

  identifier_type:
    description: "Set to True for a group. Set to false for a user."
    type: str

  is_group:
    description: "Set to True for a group. Set to false for a user."
    type: bool

  name:
    description: "A user name or group name."
    type: str

  quota_group_id:
    description: "The ID of the quota group to which the user/group quota should be added. Requires VMS 5.5 or later."
    type: int

  quota_id:
    description: "The ID of the quota to which the user/group quota should be added."
    type: int

  soft_limit:
    description: "Storage usage limit at which warnings of exceeding the quota are issued."
    type: int

  soft_limit_inodes:
    description: |
      Number of directories and unique files under the path at which warnings of exceeding the quota will be issued. A
      file with multiple hardlinks is counted only once.
    type: int
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create UserQuota
  vastdata.vms.userquotas:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    state: present

- name: Update UserQuota
  vastdata.vms.userquotas:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete UserQuota
  vastdata.vms.userquotas:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
userquotas:
  description: The userquotas resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "grace_period": {"type": "str", "default": None},
    "hard_limit": {"type": "int", "default": None},
    "hard_limit_inodes": {"type": "int", "default": None},
    "identifier": {"type": "str", "default": None},
    "identifier_type": {"type": "str", "default": None},
    "is_group": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "quota_group_id": {"type": "int", "default": None},
    "quota_id": {"type": "int", "default": None},
    "soft_limit": {"type": "int", "default": None},
    "soft_limit_inodes": {"type": "int", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class UserquotaResource(BaseResource):
    """Resource manager for UserQuota."""

    resource_name = "userquotas"
    singular = "userquota"
    lookup_field = "name"
    create_only_fields = {
        "identifier",
        "identifier_type",
        "is_group",
        "name",
        "quota_group_id",
        "quota_id",
    }  # Fields only valid during creation
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "quota_group_id": {"min": (5, 5), "max": None},
    }
    field_transforms = {
        (5, 5): {
            "hard_limit": {"request": "to_string", "response": "to_int"},
            "soft_limit": {"request": "to_string", "response": "to_int"},
        },
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = UserquotaResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
