#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: userquotas_info
short_description: List VAST UserQuota resources
description:
  - List VAST UserQuota resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  entity_identifier:
    description: "Filter by entity identifier (optional filter)"
    type: str

  guid:
    description: "Quota guid (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  identifier:
    description: "Filter by identifier (optional filter)"
    type: str

  identifier_type:
    description: "Filter by identifier type (optional filter)"
    type: str

  is_group:
    description: "Filter by is group (optional filter)"
    type: bool

  name:
    description: "The name (optional filter)"
    type: str

  path:
    description: "Filter by path (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all userquotas
  vastdata.vms.userquotas_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: userquotas_result

- name: List userquotas filtered by name
  vastdata.vms.userquotas_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_userquotas
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
userquotas:
  description: List of matching userquotas resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "entity_identifier": {"type": "str", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "identifier": {"type": "str", "default": None},
    "identifier_type": {"type": "str", "default": None},
    "is_group": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "path": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class UserquotaInfoResource(BaseInfoResource):
    """Read-only list manager for UserQuota."""

    resource_name = "userquotas"
    return_key = "userquotas"
    filter_fields = {"entity_identifier", "guid", "id", "identifier", "identifier_type", "is_group", "name", "path"}
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "quota_group_id": {"min": (5, 5), "max": None},
    }
    field_transforms = {
        (5, 5): {
            "hard_limit": {"request": "to_string", "response": "to_int"},
            "soft_limit": {"request": "to_string", "response": "to_int"},
        },
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = UserquotaInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
