#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: users_info
short_description: List VAST User resources
description:
  - List VAST User resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  allow_create_bucket:
    description: |
      If enabled, the user has permission to create S3 buckets. In case of conflict with an S3 identity policy attached
      to the user or to a elevant group, this setting is overridden. (optional filter)
    type: bool

  allow_delete_bucket:
    description: |
      If enabled, the user has permission to delete S3 buckets. In case of conflict with an S3 identity policy attached
      to the user or to a relevant group, this setting is overridden (optional filter)
    type: bool

  group_count:
    description: "Group Count (optional filter)"
    type: int

  guid:
    description: "Global unique ID (optional filter)"
    type: str

  id:
    description: "Filter by id (optional filter)"
    type: int

  is_temporary_password:
    description: "Password is temporary (optional filter)"
    type: bool

  leading_gid:
    description: "Leading GID (optional filter)"
    type: int

  leading_group_gid:
    description: "Leading Group GID (optional filter)"
    type: int

  leading_group_name:
    description: "Leading Group (optional filter)"
    type: str

  local:
    description: "not in use (optional filter)"
    type: bool

  name:
    description: "The name of the user (optional filter)"
    type: str

  password_is_set:
    description: "Password is set (optional filter)"
    type: bool

  primary_group_sid:
    description: "Primary group SID (optional filter)"
    type: str

  s3_superuser:
    description: |
      If enabled, the user has S3 superuser permission, which overrides S3 ACLs. In case of conflict with an S3
      identity policy attached to the user or to a relevant group, this setting is overridden. (optional filter)
    type: bool

  sid:
    description: "SID (optional filter)"
    type: str

  title:
    description: "Filter by title (optional filter)"
    type: str

  uid:
    description: "UID (optional filter)"
    type: int

  url:
    description: "Endpoint URL for API operations on the user (optional filter)"
    type: str

  vid:
    description: "User's VAST ID (optional filter)"
    type: int
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all users
  vastdata.vms.users_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: users_result

- name: List users filtered by name
  vastdata.vms.users_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_users
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
users:
  description: List of matching users resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "allow_create_bucket": {"type": "bool", "default": None},
    "allow_delete_bucket": {"type": "bool", "default": None},
    "group_count": {"type": "int", "default": None},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "is_temporary_password": {"type": "bool", "default": None, "no_log": True},
    "leading_gid": {"type": "int", "default": None},
    "leading_group_gid": {"type": "int", "default": None},
    "leading_group_name": {"type": "str", "default": None},
    "local": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "password_is_set": {"type": "bool", "default": None, "no_log": True},
    "primary_group_sid": {"type": "str", "default": None},
    "s3_superuser": {"type": "bool", "default": None},
    "sid": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "uid": {"type": "int", "default": None},
    "url": {"type": "str", "default": None},
    "vid": {"type": "int", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class UserInfoResource(BaseInfoResource):
    """Read-only list manager for User."""

    resource_name = "users"
    return_key = "users"
    filter_fields = {
        "allow_create_bucket",
        "allow_delete_bucket",
        "group_count",
        "guid",
        "id",
        "is_temporary_password",
        "leading_gid",
        "leading_group_gid",
        "leading_group_name",
        "local",
        "name",
        "password_is_set",
        "primary_group_sid",
        "s3_superuser",
        "sid",
        "title",
        "uid",
        "url",
        "vid",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = UserInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
