#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: viewpolicies
short_description: Manage VAST ViewPolicy resources
description:
  - Create, update, or delete VAST ViewPolicy resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  access_flavor:
    description: |
      Applicable with MIXED_LAST_WINS security flavor (Access can be set via NFSv3 regardless of this option)
    type: str
    choices: ["NFS4", "SMB", "ALL"]

  allowed_characters:
    description: "Specifies the policy for which characters are allowed in file names."
    type: str
    choices: ["LCD", "NPL"]

  apple_sid:
    description: |
      For use when connecting from Mac clients to SMB shares, this option enables Security IDs (SIDs) to be returned in
      Apple compatible representation.
    type: bool

  atime_frequency:
    description: |
      Frequency for updating the atime attribute of NFS files. atime is updated on read operations if the difference
      between the current time and the file's atime value is greater than the atime frequency. For example: 300 or
      00:00:30 seconds is supported. Zero value is not supported. Default: 3600
    type: str

  auth_source:
    description: |
      Specifies which source is trusted for the user's group memberships, when users' access to the view is authorized.
    type: str
    choices: ["RPC", "PROVIDERS", "RPC_AND_PROVIDERS"]

  cluster_id:
    description: "Cluster Id"
    type: int

  disable_handle_lease:
    description: "Disable Handle Lease"
    type: bool

  disable_read_lease:
    description: "Disable Read Lease"
    type: bool

  disable_write_lease:
    description: "Disable Write Lease"
    type: bool

  enable_access_to_snapshot_dir_in_subdirs:
    description: "Specifies whether to make the .snapshot directory accessible in subdirectories of the View."
    type: bool

  enable_visibility_of_snapshot_dir:
    description: "Specifies whether to make the .snapshot directory visible in subdirectories of the View."
    type: bool

  expose_id_in_fsid:
    description: "Expose Id In Fsid"
    type: bool

  flavor:
    description: |
      Sets the security flavor, which determines how file and directory permissions are applied in multiprotocol views
    type: str
    choices: ["NFS", "SMB", "MIXED_LAST_WINS", "S3_NATIVE"]

  gid_inheritance:
    description: "GID inheritance. BSD - Inherit the GID from the parent folder. LINUX - Inherit the GID from the user."
    type: str
    choices: ["BSD", "LINUX"]

  inherit_parent_mode_bits:
    description: "Enable NFS behavior of inheriting POSIX settings from the parent directory versus configured values. "
    type: bool

  is_s3_default_policy:
    description: "Specifies whether to make the view policy the default policy used for S3 endpoint views."
    type: bool

  name:
    description: "Name"
    type: str

  nfs_all_squash:
    description: |
      Specify which NFS client hosts have all squash. With all squash, all client users are mapped to nobody for all
      file and folder management operations on the export. Specify array of hosts separated by commas. Each host can be
      specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of IPs indicated by an IP
      address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  nfs_case_insensitive:
    description: "Force case insensitivity for NFSv3 and NFSv4"
    type: bool

  nfs_enforce_tls:
    description: |
      Accept NFSv3 and NFSv4 client mounts only if they are TLS-encrypted. Use only with Minimal Protection Level set
      to System or None.
    type: bool

  nfs_enforce_tls_relaxed:
    description: |
      Whether to relax TLS enforcement by not requiring TLS for auxiliary NFSv3 sub-protocols | (MOUNT, NLM, NSM,
      RQUOTA, NFSACL)
    type: bool

  nfs_minimal_protection_level:
    description: |
      For a policy intended for use with NFSv4-enabled views, sets the Minimal Protection Level for NFSv4 client
      mounts: 'KRB_AUTH_ONLY' allows client mounts with Kerberos authentication only (using the RPCSEC_GSS
      authentication service), 'SYSTEM' allows client mounts using either the AUTH_SYS RCP security flavor (the
      traditional default NFS authentication scheme) or with Kerberos authentication, 'NONE' (default) allows client
      mounts with the AUTH_NONE (anonymous access), or AUTH_SYS RCP security flavors, or with Kerberos authentication.
    type: str

  nfs_no_squash:
    description: |
      Specify which NFS client hosts have no squash. With no squash, all operations are supported. Use this option if
      you trust the root user not to perform operations that will corrupt data. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  nfs_posix_acl:
    description: "Enables full support of extended POSIX Access Control Lists (ACL)"
    type: bool

  nfs_read_only:
    description: |
      Specify which NFS client hosts can access the view with read-only access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  nfs_read_write:
    description: |
      Specify which NFS client hosts can access the view with read-write access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  nfs_return_open_permissions:
    description: |
      If enabled for NFS-exposed views, the NFS server unilaterally returns open (777) permission for all files and
      directories when responding to client side access checks
    type: bool

  nfs_root_squash:
    description: |
      Specify which NFS client hosts have root squash. With root squash, the root user is mapped to nobody for all file
      and folder management operations on the export. This enables you to prevent the strongest super user from
      corrupting all user data on the VAST Cluster. Specify array of hosts separated by commas. Each host can be
      specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of IPs indicated by an IP
      address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  path_length:
    description: "Specifies the policy for limiting file path component name length."
    type: str
    choices: ["LCD", "NPL"]

  permission_per_vip_pool:
    description: "VIP pools permissions map - {vippol_id: permission}. Example - {1: 'RW'}."
    type: dict

  protocols:
    description: "Array of protocols to audit"
    type: list
    elements: str

  protocols_audit:
    description: |
      Specify audit options to enable them for all attached views in addition to auditing options that are enabled
      globably on the cluster.
    type: dict

  read_only:
    description: |
      Specify which NFS client hosts can access the view with read-only access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  read_write:
    description: |
      Specify which NFS client hosts can access the view with read-write access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  s3_bucket_acl:
    description: "S3 Bucket Acl"
    type: dict

  s3_flavor_allow_free_listing:
    description: |
      Allow NFS clients freely list bucket views and their subdirectories, regardless of individual object permissions.
    type: bool

  s3_flavor_detect_full_pathname:
    description: |
      When this flag is enabled in S3 flavor, NFS access to objects is determined based on the full resource names
      specified in the identity policies. When disabled, only the bucket name is compared to the identity policy.
    type: bool

  s3_object_acl:
    description: "S3 Object Acl"
    type: dict

  s3_read_only:
    description: |
      Specify which S3 client hosts can access the view with read-only access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  s3_read_write:
    description: |
      Specify which S3 client hosts can access the view with read-write access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  s3_special_chars_support:
    description: |
      This will enable object names that contain \"//\" or \"/../\" and are incompatible with other protocols
    type: bool

  s3_visibility:
    description: |
      Users with permission to list buckets that are created using this policy even if they do not have permission to
      access those buckets.
    type: list
    elements: str

  s3_visibility_groups:
    description: |
      Users with permission to list buckets that are created using this policy even if they do not have permission to
      access those buckets.
    type: list
    elements: str

  smb_directory_mode:
    description: |
      For multiprotocol views, if the security flavor is NFS, this parameter sets default unix permission bits for
      directories created by SMB clients. Use three digit numeric notation, each digit representing the user, group and
      others compontents of the permissions, in that order. Each digit is the sum of the read bit, write bit and
      execute bit. If reading is permitted, the read bit adds 4 to the component. If writing is permitted, the write
      bit adds 2 to the component. If execution is permitted, the execute bit adds 1 to the component.
    type: int

  smb_file_mode:
    description: |
      For multiprotocol views, if the security flavor is NFS, this parameter sets default unix permission bits for
      files created by SMB clients. Use three digit numeric notation, each digit representing the user, group and
      others compontents of the permissions, in that order. Each digit is the sum of the read bit, write bit and
      execute bit. If reading is permitted, the read bit adds 4 to the component. If writing is permitted, the write
      bit adds 2 to the component. If execution is permitted, the execute bit adds 1 to the component.
    type: int

  smb_is_ca:
    description: |
      When enabled, the SMB share exposed by the view is set as continuously available, which allows SMB3 clients to
      request use of persistent file handles and keep their connections to this share in case of a failover event.
    type: bool

  smb_read_only:
    description: |
      Specify which SMB client hosts can access the view with read-only access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  smb_read_write:
    description: |
      Specify which SMB client hosts can access the view with read-write access. Specify array of hosts separated by
      commas. Each host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of
      IPs indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address.
    type: list
    elements: str

  tenant_id:
    description: "Tenant ID"
    type: int

  trash_access:
    description: |
      Specify which NFSv3 client hosts can access the trash folder. Specify array of hosts separated by commas. Each
      host can be specified as an IP address, a netgroup key beginning with @, a CIDR subnet or a range of IPs
      indicated by an IP address with a * as a wildcard in place of any of the 8-bit fields in the IP address. Trash
      folder access must also be enabled for the cluster.
    type: list
    elements: str

  use_32bit_fileid:
    description: |
      Sets the VAST Cluster's NFS server to use 32bit file IDs. This setting supports legacy 32-bit applications
      running over NFS.
    type: str

  use_auth_provider:
    description: "Not in use"
    type: bool
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create ViewPolicy
  vastdata.vms.viewpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-name"
    state: present

- name: Update ViewPolicy
  vastdata.vms.viewpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete ViewPolicy
  vastdata.vms.viewpolicies:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
viewpolicies:
  description: The viewpolicies resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "access_flavor": {"type": "str", "default": None, "choices": ["NFS4", "SMB", "ALL"]},
    "allowed_characters": {"type": "str", "default": None, "choices": ["LCD", "NPL"]},
    "apple_sid": {"type": "bool", "default": None},
    "atime_frequency": {"type": "str", "default": None},
    "auth_source": {"type": "str", "default": None, "choices": ["RPC", "PROVIDERS", "RPC_AND_PROVIDERS"]},
    "cluster_id": {"type": "int", "default": None},
    "disable_handle_lease": {"type": "bool", "default": None},
    "disable_read_lease": {"type": "bool", "default": None},
    "disable_write_lease": {"type": "bool", "default": None},
    "enable_access_to_snapshot_dir_in_subdirs": {"type": "bool", "default": None},
    "enable_visibility_of_snapshot_dir": {"type": "bool", "default": None},
    "expose_id_in_fsid": {"type": "bool", "default": None},
    "flavor": {"type": "str", "default": None, "choices": ["NFS", "SMB", "MIXED_LAST_WINS", "S3_NATIVE"]},
    "gid_inheritance": {"type": "str", "default": None, "choices": ["BSD", "LINUX"]},
    "inherit_parent_mode_bits": {"type": "bool", "default": None},
    "is_s3_default_policy": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "nfs_all_squash": {"type": "list", "default": None, "elements": "str"},
    "nfs_case_insensitive": {"type": "bool", "default": None},
    "nfs_enforce_tls": {"type": "bool", "default": None},
    "nfs_enforce_tls_relaxed": {"type": "bool", "default": None},
    "nfs_minimal_protection_level": {"type": "str", "default": None},
    "nfs_no_squash": {"type": "list", "default": None, "elements": "str"},
    "nfs_posix_acl": {"type": "bool", "default": None},
    "nfs_read_only": {"type": "list", "default": None, "elements": "str"},
    "nfs_read_write": {"type": "list", "default": None, "elements": "str"},
    "nfs_return_open_permissions": {"type": "bool", "default": None},
    "nfs_root_squash": {"type": "list", "default": None, "elements": "str"},
    "path_length": {"type": "str", "default": None, "choices": ["LCD", "NPL"]},
    "permission_per_vip_pool": {"type": "dict", "default": None},
    "protocols": {"type": "list", "default": None, "elements": "str"},
    "protocols_audit": {"type": "dict", "default": None},
    "read_only": {"type": "list", "default": None, "elements": "str"},
    "read_write": {"type": "list", "default": None, "elements": "str"},
    "s3_bucket_acl": {"type": "dict", "default": None},
    "s3_flavor_allow_free_listing": {"type": "bool", "default": None},
    "s3_flavor_detect_full_pathname": {"type": "bool", "default": None},
    "s3_object_acl": {"type": "dict", "default": None},
    "s3_read_only": {"type": "list", "default": None, "elements": "str"},
    "s3_read_write": {"type": "list", "default": None, "elements": "str"},
    "s3_special_chars_support": {"type": "bool", "default": None},
    "s3_visibility": {"type": "list", "default": None, "elements": "str"},
    "s3_visibility_groups": {"type": "list", "default": None, "elements": "str"},
    "smb_directory_mode": {"type": "int", "default": None},
    "smb_file_mode": {"type": "int", "default": None},
    "smb_is_ca": {"type": "bool", "default": None},
    "smb_read_only": {"type": "list", "default": None, "elements": "str"},
    "smb_read_write": {"type": "list", "default": None, "elements": "str"},
    "tenant_id": {"type": "int", "default": None},
    "trash_access": {"type": "list", "default": None, "elements": "str"},
    "use_32bit_fileid": {"type": "str", "default": None},
    "use_auth_provider": {"type": "bool", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ViewpolicyResource(BaseResource):
    """Resource manager for ViewPolicy."""

    resource_name = "viewpolicies"
    singular = "viewpolicy"
    lookup_field = "name"


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ViewpolicyResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
