#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: viewpolicies_info
short_description: List VAST ViewPolicy resources
description:
  - List VAST ViewPolicy resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  access_flavor:
    description: |
      Applicable with MIXED_LAST_WINS security flavor (Access can be set via NFSv3 regardless of this option) (optional
      filter)
    type: str

  allowed_characters:
    description: |
      How to determine which characters are allowed in file names. 'LCD' (default): Allows only characters allowed by
      all VAST Cluster-supported protocols, regardless of the specific protocol enabled on a specific view. With this
      (default) option, the limitation on the length of a single component of the path is 255 characters. 'NPL':
      Imposes no limitation beyond that of the client protocol. (optional filter)
    type: str
    choices: ["LCD", "NPL"]

  apple_sid:
    description: |
      For use when connecting from Mac clients to SMB shares, this option enables Security IDs (SIDs) to be returned in
      Apple compatible representation. (optional filter)
    type: bool

  atime_frequency:
    description: |
      Frequency for updating the atime attribute of NFS files. atime is updated on read operations if the difference
      between the current time and the file's atime value is greater than the atime frequency. Default: 3600 (optional
      filter)
    type: str

  auth_source:
    description: |
      Specifies which source is trusted for the user's group memberships, when users' access to the view is authorized.
      (optional filter)
    type: str
    choices: ["RPC", "PROVIDERS", "RPC_AND_PROVIDERS"]

  cluster:
    description: "Parent Cluster (optional filter)"
    type: str

  cluster_id:
    description: "Parent Cluster ID (optional filter)"
    type: int

  count_views:
    description: "Number of Policy related Views (optional filter)"
    type: int

  created:
    description: "Filter by created (optional filter)"
    type: str

  data_create_delete:
    description: "Create/Delete Files/Directories/Objects (optional filter)"
    type: bool

  data_modify:
    description: "Modify data/MD (optional filter)"
    type: bool

  data_read:
    description: "Read data (optional filter)"
    type: bool

  disable_handle_lease:
    description: "Filter by disable handle lease (optional filter)"
    type: bool

  disable_read_lease:
    description: "Filter by disable read lease (optional filter)"
    type: bool

  disable_write_lease:
    description: "Filter by disable write lease (optional filter)"
    type: bool

  enable_access_to_snapshot_dir_in_subdirs:
    description: |
      Specifies whether to make the .snapshot directory visible in subdirectories of the View. (optional filter)
    type: bool

  enable_listing_of_snapshot_dir:
    description: |
      Specifies whether to make the .snapshot directory visible in subdirectories of the View. (optional filter)
    type: bool

  enable_snapshot_lookup:
    description: |
      Specifies whether to make the .snapshot directory accessible in subdirectories of the View. (optional filter)
    type: bool

  enable_visibility_of_snapshot_dir:
    description: |
      Specifies whether to make the .snapshot directory visible in subdirectories of the View. (optional filter)
    type: bool

  expose_id_in_fsid:
    description: "Filter by expose id in fsid (optional filter)"
    type: bool

  flavor:
    description: |
      Security flavor, which determines how file and directory permissions are applied in multiprotocol views.
      (optional filter)
    type: str
    choices: ["NFS", "SMB", "MIXED_LAST_WINS", "S3_NATIVE"]

  gid_inheritance:
    description: |
      Specifies how files receive their owning group when they are created. 'LINUX' (default): Each new file inherits
      its owning group from the group ID of the user who creates the file. 'BSD': Each new file inherits its owning
      group from the group ID of the parent directory. (optional filter)
    type: str
    choices: ["BSD", "LINUX"]

  guid:
    description: "Globally unique identifier (optional filter)"
    type: str

  id:
    description: "ID (optional filter)"
    type: int

  inherit_parent_mode_bits:
    description: |
      Enable NFS behavior of inheriting POSIX settings from the parent directory versus configured values. (optional
      filter)
    type: bool

  internal:
    description: "Filter by internal (optional filter)"
    type: bool

  is_block_default_policy:
    description: "Specifies whether to make this View Policy default for BLOCK (optional filter)"
    type: bool

  is_s3_default_policy:
    description: "Specifies whether to make this View Policy default for S3 (optional filter)"
    type: bool

  log_deleted:
    description: "Log deleted files/dirs from trash dir (optional filter)"
    type: bool

  log_full_path:
    description: "Log full path (optional filter)"
    type: bool

  log_hostname:
    description: "Log hostname (optional filter)"
    type: bool

  log_username:
    description: "Log username (optional filter)"
    type: bool

  name:
    description: "Name of the policy (optional filter)"
    type: str

  nfs_case_insensitive:
    description: "Force case insensitivity for NFSv3 and NFSv4 (optional filter)"
    type: bool

  nfs_enforce_mtls:
    description: "Specifies whether we enforce mTLS authentication over NFS. (optional filter)"
    type: bool

  nfs_enforce_tls:
    description: |
      Accept NFSv3 and NFSv4 client mounts only if they are TLS-encrypted. Use only with Minimal Protection Level set
      to System or None. (optional filter)
    type: bool

  nfs_enforce_tls_relaxed:
    description: |
      Whether to relax TLS enforcement by not requiring TLS for auxiliary NFSv3 sub-protocols | (MOUNT, NLM, NSM,
      RQUOTA, NFSACL) (optional filter)
    type: bool

  nfs_minimal_protection_level:
    description: |
      Minimal Protection Level for NFSv4 client mounts: 'KRB_AUTH_ONLY' allows client mounts with Kerberos
      authentication only (using the RPCSEC_GSS authentication service), 'SYSTEM' allows client mounts using either the
      AUTH_SYS RCP security flavor (the traditional default NFS authentication scheme) or with Kerberos authentication,
      'NONE' (default) allows client mounts with the AUTH_NONE (anonymous access), or AUTH_SYS RCP security flavors, or
      with Kerberos authentication. (optional filter)
    type: str
    choices: ["NONE", "SYSTEM", "KRB_AUTH_ONLY", "KRB_INTEGRITY", "KRB_PRIVACY"]

  nfs_posix_acl:
    description: |
      True if support is enabled for extended POSIX Access Control Lists (ACL) for NFSv3 clients. (optional filter)
    type: bool

  nfs_return_open_permissions:
    description: "when using smb use open permissions for files (optional filter)"
    type: bool

  path_length:
    description: |
      How to determine the maximum allowed path component name length. 'LCD' (default): Imposes the lowest common
      denominator file length limit of all VAST Cluster-supported protocols, regardless of the specific protocol
      enabled on a specific view. 'NPL': Imposes no limitation beyond that of the client protocol. (optional filter)
    type: str
    choices: ["LCD", "NPL"]

  pretty_atime_frequency:
    description: "Filter by pretty atime frequency (optional filter)"
    type: str

  pretty_auth_source:
    description: "Filter by pretty auth source (optional filter)"
    type: str

  s3_bucket_listing:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_bucket_read:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_bucket_read_acp:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_bucket_write:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_bucket_write_acp:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_flavor_allow_free_listing:
    description: |
      Allow NFS clients freely list bucket views and their subdirectories, regardless of individual object permissions.
      (optional filter)
    type: bool

  s3_flavor_detect_full_pathname:
    description: |
      When this flag is enabled in S3 flavor, NFS access to objects is determined based on the full resource names
      specified in the identity policies. When disabled, only the bucket name is compared to the identity policy.
      (optional filter)
    type: bool

  s3_object_full_control:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_object_read:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_object_read_acp:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_object_write:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_object_write_acp:
    description: "Hosts with full permissions (optional filter)"
    type: str

  s3_special_chars_support:
    description: |
      This will enable object names that contain \"//\" or \"/../\" and are incompatible with other protocols (optional
      filter)
    type: bool

  smb_directory_mode:
    description: "Default unix type permissions on new folder (optional filter)"
    type: int

  smb_directory_mode_padded:
    description: "Default unix type permissions on new folder (optional filter)"
    type: str

  smb_file_mode:
    description: "Default unix type permissions on new file (optional filter)"
    type: int

  smb_file_mode_padded:
    description: "Default unix type permissions on new file (optional filter)"
    type: str

  smb_is_ca:
    description: |
      When enabled, the SMB share exposed by the view is set as continuously available, which allows SMB3 clients to
      request use of persistent file handles and keep their connections to this share in case of a failover event.
      (optional filter)
    type: bool

  smb_recursive_change_notify:
    description: "Whether SMB Recursive Change Notify is enabled (optional filter)"
    type: bool

  sync:
    description: "Synchronization state with leader (optional filter)"
    type: str

  sync_time:
    description: "Synchronization time with leader (optional filter)"
    type: str

  tenant_id:
    description: "Tenant ID (optional filter)"
    type: int

  tenant_name:
    description: "Tenant Name (optional filter)"
    type: str

  title:
    description: "Filter by title (optional filter)"
    type: str

  url:
    description: "Endpoint URL for API operations on the view policy object (optional filter)"
    type: str

  use_32bit_fileid:
    description: |
      If true, the VAST Cluster's NFS server uses 32bit file IDs. This setting supports legacy 32-bit applications
      running over NFS. (optional filter)
    type: bool

  use_auth_provider:
    description: "Not in use (optional filter)"
    type: bool
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all viewpolicies
  vastdata.vms.viewpolicies_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: viewpolicies_result

- name: List viewpolicies filtered by name
  vastdata.vms.viewpolicies_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_viewpolicies
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
viewpolicies:
  description: List of matching viewpolicies resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "access_flavor": {"type": "str", "default": None},
    "allowed_characters": {"type": "str", "default": None, "choices": ["LCD", "NPL"]},
    "apple_sid": {"type": "bool", "default": None},
    "atime_frequency": {"type": "str", "default": None},
    "auth_source": {"type": "str", "default": None, "choices": ["RPC", "PROVIDERS", "RPC_AND_PROVIDERS"]},
    "cluster": {"type": "str", "default": None},
    "cluster_id": {"type": "int", "default": None},
    "count_views": {"type": "int", "default": None},
    "created": {"type": "str", "default": None},
    "data_create_delete": {"type": "bool", "default": None},
    "data_modify": {"type": "bool", "default": None},
    "data_read": {"type": "bool", "default": None},
    "disable_handle_lease": {"type": "bool", "default": None},
    "disable_read_lease": {"type": "bool", "default": None},
    "disable_write_lease": {"type": "bool", "default": None},
    "enable_access_to_snapshot_dir_in_subdirs": {"type": "bool", "default": None},
    "enable_listing_of_snapshot_dir": {"type": "bool", "default": None},
    "enable_snapshot_lookup": {"type": "bool", "default": None},
    "enable_visibility_of_snapshot_dir": {"type": "bool", "default": None},
    "expose_id_in_fsid": {"type": "bool", "default": None},
    "flavor": {"type": "str", "default": None, "choices": ["NFS", "SMB", "MIXED_LAST_WINS", "S3_NATIVE"]},
    "gid_inheritance": {"type": "str", "default": None, "choices": ["BSD", "LINUX"]},
    "guid": {"type": "str", "default": None},
    "id": {"type": "int", "default": None},
    "inherit_parent_mode_bits": {"type": "bool", "default": None},
    "internal": {"type": "bool", "default": None},
    "is_block_default_policy": {"type": "bool", "default": None},
    "is_s3_default_policy": {"type": "bool", "default": None},
    "log_deleted": {"type": "bool", "default": None},
    "log_full_path": {"type": "bool", "default": None},
    "log_hostname": {"type": "bool", "default": None},
    "log_username": {"type": "bool", "default": None},
    "name": {"type": "str", "default": None},
    "nfs_case_insensitive": {"type": "bool", "default": None},
    "nfs_enforce_mtls": {"type": "bool", "default": None},
    "nfs_enforce_tls": {"type": "bool", "default": None},
    "nfs_enforce_tls_relaxed": {"type": "bool", "default": None},
    "nfs_minimal_protection_level": {
        "type": "str",
        "default": None,
        "choices": ["NONE", "SYSTEM", "KRB_AUTH_ONLY", "KRB_INTEGRITY", "KRB_PRIVACY"],
    },
    "nfs_posix_acl": {"type": "bool", "default": None},
    "nfs_return_open_permissions": {"type": "bool", "default": None},
    "path_length": {"type": "str", "default": None, "choices": ["LCD", "NPL"]},
    "pretty_atime_frequency": {"type": "str", "default": None},
    "pretty_auth_source": {"type": "str", "default": None},
    "s3_bucket_listing": {"type": "str", "default": None},
    "s3_bucket_read": {"type": "str", "default": None},
    "s3_bucket_read_acp": {"type": "str", "default": None},
    "s3_bucket_write": {"type": "str", "default": None},
    "s3_bucket_write_acp": {"type": "str", "default": None},
    "s3_flavor_allow_free_listing": {"type": "bool", "default": None},
    "s3_flavor_detect_full_pathname": {"type": "bool", "default": None},
    "s3_object_full_control": {"type": "str", "default": None},
    "s3_object_read": {"type": "str", "default": None},
    "s3_object_read_acp": {"type": "str", "default": None},
    "s3_object_write": {"type": "str", "default": None},
    "s3_object_write_acp": {"type": "str", "default": None},
    "s3_special_chars_support": {"type": "bool", "default": None},
    "smb_directory_mode": {"type": "int", "default": None},
    "smb_directory_mode_padded": {"type": "str", "default": None},
    "smb_file_mode": {"type": "int", "default": None},
    "smb_file_mode_padded": {"type": "str", "default": None},
    "smb_is_ca": {"type": "bool", "default": None},
    "smb_recursive_change_notify": {"type": "bool", "default": None},
    "sync": {"type": "str", "default": None},
    "sync_time": {"type": "str", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "tenant_name": {"type": "str", "default": None},
    "title": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
    "use_32bit_fileid": {"type": "bool", "default": None},
    "use_auth_provider": {"type": "bool", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class ViewpolicyInfoResource(BaseInfoResource):
    """Read-only list manager for ViewPolicy."""

    resource_name = "viewpolicies"
    return_key = "viewpolicies"
    filter_fields = {
        "access_flavor",
        "allowed_characters",
        "apple_sid",
        "atime_frequency",
        "auth_source",
        "cluster",
        "cluster_id",
        "count_views",
        "created",
        "data_create_delete",
        "data_modify",
        "data_read",
        "disable_handle_lease",
        "disable_read_lease",
        "disable_write_lease",
        "enable_access_to_snapshot_dir_in_subdirs",
        "enable_listing_of_snapshot_dir",
        "enable_snapshot_lookup",
        "enable_visibility_of_snapshot_dir",
        "expose_id_in_fsid",
        "flavor",
        "gid_inheritance",
        "guid",
        "id",
        "inherit_parent_mode_bits",
        "internal",
        "is_block_default_policy",
        "is_s3_default_policy",
        "log_deleted",
        "log_full_path",
        "log_hostname",
        "log_username",
        "name",
        "nfs_case_insensitive",
        "nfs_enforce_mtls",
        "nfs_enforce_tls",
        "nfs_enforce_tls_relaxed",
        "nfs_minimal_protection_level",
        "nfs_posix_acl",
        "nfs_return_open_permissions",
        "path_length",
        "pretty_atime_frequency",
        "pretty_auth_source",
        "s3_bucket_listing",
        "s3_bucket_read",
        "s3_bucket_read_acp",
        "s3_bucket_write",
        "s3_bucket_write_acp",
        "s3_flavor_allow_free_listing",
        "s3_flavor_detect_full_pathname",
        "s3_object_full_control",
        "s3_object_read",
        "s3_object_read_acp",
        "s3_object_write",
        "s3_object_write_acp",
        "s3_special_chars_support",
        "smb_directory_mode",
        "smb_directory_mode_padded",
        "smb_file_mode",
        "smb_file_mode_padded",
        "smb_is_ca",
        "smb_recursive_change_notify",
        "sync",
        "sync_time",
        "tenant_id",
        "tenant_name",
        "title",
        "url",
        "use_32bit_fileid",
        "use_auth_provider",
    }
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for
    field_versions = {
        "is_block_default_policy": {"min": (5, 5), "max": None},
        "nfs_enforce_mtls": {"min": (5, 5), "max": None},
        "s3_bucket_full_control": {"min": (5, 5), "max": None},
        "smb_recursive_change_notify": {"min": (5, 5), "max": None},
        "vip_pools": {"min": (5, 5), "max": None},
    }


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = ViewpolicyInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
