#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: vippools
short_description: Manage VAST VIPPool resources
description:
  - Create, update, or delete VAST VIPPool resources.
  - Supports check_mode and diff for idempotent operations.
version_added: "1.0.0"
options:
  vms:
    description: VAST VMS connection parameters.
    type: dict
    required: true
    suboptions:
      host:
        description: VAST VMS hostname or IP address.
        required: true
        type: str
      validate_certs:
        description: Validate SSL certificates.
        type: bool
        default: true
      timeout:
        description: Request timeout in seconds.
        type: int
      token:
        description: API token (VAST 5.3+). Mutually exclusive with username/password.
        type: str
      username:
        description: Username for authentication. Mutually exclusive with token.
        type: str
      password:
        description: Password for authentication. Mutually exclusive with token.
        type: str
      tenant:
        description: Tenant name (optional).
        type: str
      api_version:
        description: API version (optional). Defaults to 'latest' if not specified.
        type: str
  id:
    description: Resource ID for direct lookup. Mutually exclusive with name-based identification.
    type: int
  bgp_config_id:
    description: "BGP configuration ID for the VIP pool"
    type: int

  client_monitoring_ips:
    description: "External client monitoring IP ranges for VIP pool connectivity monitoring"
    type: list
    elements: list

  cluster_id:
    description: "Cluster Id"
    type: int

  cnode_ids:
    description: |
      Dedicates a specific group of CNodes to the VIP pool. List the IDs of the CNodes. Separate IDs by commas. This is
      a way to dedicate a specific set of CNodes to a specific set of client hosts or applications. Overridden if
      cnode_names is passed.
    type: list
    elements: int

  cnode_names:
    description: |
      Dedicates a specific group of CNodes to the VIP pool. List the names of the CNodes. Separate names by commas.
      This is a way to dedicate a specific set of CNodes to a specific set of client hosts or applications. Overrides
      cnode_ids.
    type: str

  domain_name:
    description: |
      Domain name for the VAST DNS server. If a DNS configuration exists, the domain suffix defined in the DNS server
      configuration is appended to this domain name to form a FQDN which the DNS server resolves to this VIP pool.
    type: str

  enable_l3:
    description: |
      Enables L3 networking, in which the cluster's CNodes act as Border Gateway Protocol (BGP) peers belonging to a
      VAST Autonomous system (AS) which is connected to the client network's AS
    type: bool

  enable_weighted_balancing:
    description: "Enable weighted balancing"
    type: bool

  enabled:
    description: "True for enable, False for disable"
    type: bool

  end_ip:
    description: "Not currently in use. Use ip_ranges instead."
    type: str

  gw_ip:
    description: "The IP address of a local gateway device if client traffic is routed through one."
    type: str

  gw_ipv6:
    description: "The IP address of a local gateway device if client traffic is routed through one."
    type: str

  ip_ranges:
    description: "An array of IP ranges included in the vippool."
    type: list
    elements: list

  name:
    description: "The VIP pool name"
    type: str

  peer_asn:
    description: "Peer Asn"
    type: int

  port_membership:
    description: |
      Allocates left, right or all CNode ports to the VIP pool. Allocating the left port and the right port in
      different VIP pools enables the CNodes to be connected to multiple networks simultaneously. Default: all
    type: str

  role:
    description: |
      'PROTOCOLS' dedicates the VIP pool to client traffic from all of the supported access protocols (NFSv3, NFSv4.2,
      SMBv2, S3, Database). At least one VIP pool must be created to enable client access. 'REPLICATION' dedicates the
      VIP pool for connectivity with an async replication peer cluster. This is needed for async replication.
      'BIG_CATALOG' dedicates the VIP pool to VAST Catalog query access from the client network.
    type: str
    choices: ["PROTOCOLS", "REPLICATION", "BIG_CATALOG", "QUERY_ENGINE_CNODE_GROUP"]

  start_ip:
    description: "Not currently in use. Use ip_ranges instead."
    type: str

  subnet_cidr:
    description: "The subnet expressed as a CIDR index (number of bits in each IP that belong to the subnet)"
    type: int

  subnet_cidr_ipv6:
    description: "The subnet expressed as a CIDR index (number of bits in each IP that belong to the subnet)"
    type: int

  tenant_id:
    description: "Tenant ID"
    type: int

  vast_asn:
    description: "Vast Asn"
    type: int

  vlan:
    description: |
      To tag the VIP pool with a specific VLAN on the data network, specify the VLAN (0-4096). The VIP pool will be
      exposed only to the specified VLAN on the client network.
    type: int

  vms_preferred:
    description: "If true, CNodes participating in the vip pool to be preferred in VMS host election."
    type: bool
  state:
    description: Desired state of the resource.
    type: str
    choices: [present, absent]
    default: present
  wait:
    description: Wait for async operations to complete.
    type: bool
    default: true
  wait_timeout:
    description: Timeout in seconds for async operations.
    type: int
    default: 300
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: full
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: Create VIPPool
  vastdata.vms.vippools:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    subnet_cidr: 1
    ip_ranges: []
    state: present

- name: Update VIPPool
  vastdata.vms.vippools:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: present

- name: Delete VIPPool
  vastdata.vms.vippools:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: "example-value"
    state: absent
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Whether a change was made.
  type: bool
  returned: always
vippools:
  description: The vippools resource data.
  type: dict
  returned: always
  sample:
    id: 1
    name: "example"
diff:
  description: Before/after diff when changed.
  type: dict
  returned: when changed
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.resource import BaseResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "id": {"type": "int", "default": None},
    "bgp_config_id": {"type": "int", "default": None},
    "client_monitoring_ips": {"type": "list", "default": None, "elements": "list"},
    "cluster_id": {"type": "int", "default": None},
    "cnode_ids": {"type": "list", "default": None, "elements": "int"},
    "cnode_names": {"type": "str", "default": None},
    "domain_name": {"type": "str", "default": None},
    "enable_l3": {"type": "bool", "default": None},
    "enable_weighted_balancing": {"type": "bool", "default": None},
    "enabled": {"type": "bool", "default": None},
    "end_ip": {"type": "str", "default": None},
    "gw_ip": {"type": "str", "default": None},
    "gw_ipv6": {"type": "str", "default": None},
    "ip_ranges": {"type": "list", "default": None, "elements": "list"},
    "name": {"type": "str", "default": None},
    "peer_asn": {"type": "int", "default": None},
    "port_membership": {"type": "str", "default": None},
    "role": {
        "type": "str",
        "default": None,
        "choices": [
            "PROTOCOLS",
            "REPLICATION",
            "BIG_CATALOG",
            "QUERY_ENGINE_CNODE_GROUP",
        ],
    },
    "start_ip": {"type": "str", "default": None},
    "subnet_cidr": {"type": "int", "default": None},
    "subnet_cidr_ipv6": {"type": "int", "default": None},
    "tenant_id": {"type": "int", "default": None},
    "vast_asn": {"type": "int", "default": None},
    "vlan": {"type": "int", "default": None},
    "vms_preferred": {"type": "bool", "default": None},
    "state": {"type": "str", "choices": ["present", "absent"], "default": "present"},
    "wait": {"type": "bool", "default": True},
    "wait_timeout": {"type": "int", "default": 300},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class VippoolResource(BaseResource):
    """Resource manager for VIPPool."""

    resource_name = "vippools"
    singular = "vippool"
    lookup_field = "name"


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = VippoolResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
