#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright: (c) 2026, VAST Data
# Apache License 2.0 (see LICENSE or https://www.apache.org/licenses/LICENSE-2.0)
# SPDX-License-Identifier: Apache-2.0

from __future__ import absolute_import, division, print_function

__metaclass__ = type

# BEGIN AUTOGENERATED DOCUMENTATION
DOCUMENTATION = r"""
---
module: webhooks_info
short_description: List VAST Webhook resources
description:
  - List VAST Webhook resources.
  - Read-only; always runs in check_mode and never reports changed.
  - Optional parameters are passed to the API as server-side query filters.
version_added: "1.0.0"
options:
  certificate_id:
    description: "ID of certificate used to secure the webhook (optional filter)"
    type: int

  certificate_name:
    description: "Name of the certificate used to secure the webhook (optional filter)"
    type: str

  data:
    description: "Webhook data (optional filter)"
    type: str

  enabled:
    description: "If true, the webhook is enabled. (optional filter)"
    type: bool

  id:
    description: "Webhook ID (optional filter)"
    type: int

  method:
    description: "Webhook compress_method (optional filter)"
    type: str
    choices: ["GET", "POST", "PUT", "PATCH", "DELETE"]

  name:
    description: "Name of the webhook (optional filter)"
    type: str

  url:
    description: "Webhook URL (optional filter)"
    type: str
author:
  - VAST Data (@vastdata)
extends_documentation_fragment:
  - vastdata.vms.conn
  - ansible.builtin.action_common_attributes
attributes:
  check_mode:
    support: full
  diff_mode:
    support: N/A
  platform:
    platforms: posix
"""
# END AUTOGENERATED DOCUMENTATION

# BEGIN AUTOGENERATED EXAMPLES
EXAMPLES = r"""
- name: List all webhooks
  vastdata.vms.webhooks_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
  register: webhooks_result

- name: List webhooks filtered by name
  vastdata.vms.webhooks_info:
    vms:
      host: vast-vms.example.com
      token: "{{ vast_token }}"
    name: example-value
  register: filtered_webhooks
"""
# END AUTOGENERATED EXAMPLES

# BEGIN AUTOGENERATED RETURN
RETURN = r"""
changed:
  description: Always false; info modules never change state.
  type: bool
  returned: always
webhooks:
  description: List of matching webhooks resources.
  type: list
  elements: dict
  returned: always
  sample: []
"""
# END AUTOGENERATED RETURN

# BEGIN AUTOGENERATED IMPORTS
from typing import Any, Dict

from ansible.module_utils.basic import AnsibleModule
from ansible_collections.vastdata.vms.plugins.module_utils.vast.errors import VastError
from ansible_collections.vastdata.vms.plugins.module_utils.vast.info_resource import BaseInfoResource

# END AUTOGENERATED IMPORTS

# BEGIN AUTOGENERATED ARGUMENT_SPEC
ARGUMENT_SPEC: Dict[str, Any] = {
    "vms": {
        "type": "dict",
        "required": True,
        "options": {
            "host": {"required": True, "type": "str"},
            "validate_certs": {"type": "bool", "default": True},
            "timeout": {"type": "int", "default": None},
            "token": {"type": "str", "default": None, "no_log": True},
            "username": {"type": "str", "default": None},
            "password": {"type": "str", "default": None, "no_log": True},
            "tenant": {"type": "str", "default": None},
            "api_version": {"type": "str", "default": None},
            "debug": {"type": "bool", "default": False},
        },
        "mutually_exclusive": [
            ("token", "username"),
            ("token", "password"),
        ],
    },
    "certificate_id": {"type": "int", "default": None},
    "certificate_name": {"type": "str", "default": None},
    "data": {"type": "str", "default": None},
    "enabled": {"type": "bool", "default": None},
    "id": {"type": "int", "default": None},
    "method": {"type": "str", "default": None, "choices": ["GET", "POST", "PUT", "PATCH", "DELETE"]},
    "name": {"type": "str", "default": None},
    "url": {"type": "str", "default": None},
}
# END AUTOGENERATED ARGUMENT_SPEC

# BEGIN AUTOGENERATED RESOURCE_CLASS


class WebhookInfoResource(BaseInfoResource):
    """Read-only list manager for Webhook."""

    resource_name = "webhooks"
    return_key = "webhooks"
    filter_fields = {"certificate_id", "certificate_name", "data", "enabled", "id", "method", "name", "url"}
    generated_min_version = (5, 4)  # oldest VMS version these modules were generated for


# END AUTOGENERATED RESOURCE_CLASS

# BEGIN AUTOGENERATED MAIN


def main() -> None:
    """Module entry point."""
    module = AnsibleModule(
        argument_spec=ARGUMENT_SPEC,
        supports_check_mode=True,
    )

    try:
        resource = WebhookInfoResource(module)
        resource.run()
    except VastError as e:
        module.fail_json(msg=str(e))


if __name__ == "__main__":
    main()
# END AUTOGENERATED MAIN
